/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Alchemy:": "炼金术:",
    "Energy": "能量",
    "Copium": "精神",
    "Power": "力量",
    "Perks": "特权",
    "Travel:": "旅行：",
    "Resources": "资源",
    "Serenity": "宁静",
    "Knowledge": "知识",
    "Mirror Mojo": "镜子魔咒",
    "Delusion": "妄想",
    "Assemble a Clockwork Toy": "组装一个发条玩具",
    "Brew a Simple Potion": "酿造一个简单的药水",
    "Combined Assembly Drill": "组合钻机",
    "Estimated Levels Gained:": "预计获得等级：",
    "Small Talk Practice": "闲聊练习",
    "Exit Bootcamp": "退出训练营",
    "of this task will produce a resource.": "这个任务将产生一个资源。",
    "Warm-Up Jog in Place": "原地慢跑热身",
    "Endurance, Tinkering": "耐力，铸补",
    "Tinkering, Charisma": "铸补，魅力",
    "The dark green button indicates travel to the next zone.": "深绿色按钮表示前往下一个区域。",
    "The resource icon indicates that each completion": "资源图标表示每次完成",
    "Brewmaster: Read an Alchemy Book": "酿酒大师：读一本炼金术方面的书",
    "Experiment with ingredients to create a potion.": "试着用各种原料制作一种药剂。",
    "Leave bootcamp and begin your journey.": "离开训练营，开始你的旅程。",
    "Estimated Energy Needed for next task:": "预计下一任务所需能量：",
    "Estimated Energy Needed:": "预计所需能量：",
    "Estimated Levels Gained for next task:": "下一任务预计获得等级：",
    ": Read an Alchemy Book": "：阅读一本炼金书",
    "Tinkering": "铸补",
    "A challenging drill combining physical": "结合物理训练的具有挑战性的训练",
    "Boost your stamina with a simple jog.": "通过简单的慢跑来增强你的耐力。",
    "Endurance": "耐力",
    "for the first time will grant a perk.": "这将是第一次给予特权。",
    "mandatory to progress to next zone.": "必须进入下一个区域。",
    "Polish your social skills with casual chat.": "通过随意的聊天来提高你的社交技巧。",
    "Practice assembling basic mechanisms.": "练习组装基本机构。",
    "stamina and careful assembly.": "耐力和细心组装。",
    "Study the ancient art of alchemy.": "学习古老的炼金术。",
    "The orange button indicates that this task is": "橙色按钮表示该任务是",
    "Tinker with your mirror while engaging in charismatic banter.": "一边摆弄镜子，一边和别人开玩笑。",
    "You cannot start another task right now": "你现在不能开始另一项任务",
    "The ★ indicates that completing this task": "★ 表示完成此任务",
    "Game Over": "游戏结束",
    "Restart": "重新开始",
    "This is your 1st Energy reset.": "这是你的第 1 次能量重置。",
    "You lose half your resources.": "你失去了一半的资源。",
    "You ran out of energy.": "你的能量耗尽了。",
    "Energy Elixir:": "能量药剂：",
    "Right-click to consume all.": "右键点击以消耗全部。",
    "This is your 2nd Energy reset.": "这是你的第 2 次能量重置。",
    "This is your 3rd Energy reset.": "这是你的第 3 次能量重置。",
    " unlocked!": " 已解锁!",
    " is 25% faster.": " 变快 25%。",
    ": Explore Dietary Options": "：探索饮食选择",
    "Assemble a Magnifying Glass": "组装一个放大镜",
    "Assemble a simple magnifying glass.": "组装一个简单的放大镜。",
    "Combined Recall Drill": "联合回忆练习",
    "Endurance, Intellect": "耐力，智力",
    "Endurance, Intellect, Alchemy": "耐力，智力，炼金术",
    "Engage strangers in conversation.": "与陌生人交谈。",
    "Head to the City Core": "前往市中心",
    "Intellect:": "智力:",
    "Learn about healthy eating habits.": "学习健康的饮食习惯。",
    "Map the City": "绘制城市地图",
    "Perception:": "感知：",
    "Sharpen your senses by noticing urban subtleties.": "通过观察城市的细微之处来增强你的感官。",
    "Spot Architectural Details": "发现建筑细节",
    "Strike up a Quick Chat": "开始快速聊天",
    "Run while recalling facts about your surroundings.": "一边跑步一边回忆周围的事情。",
    "Study the city’s layout to boost your intellect.": "研究城市的布局来提高你的智力。",
    "Venture into the bustling heart of the city.": "冒险进入繁华的市中心。",
    "Try": "试试",
    "Copy": "复制",
    "Back": "返回",
    "Degens Idle": "Degens放置",
    "Load": "加载",
    "Paste": "粘贴",
    "Music": "音乐",
    "Sound Effects": "音效",
    "Volume:": "音量:",
    "Tutorial": "教程",
    "Full Restart": "完全重新开始",
    "Buy Me a Coffee": "请作者喝杯咖啡",
    "Click to see changelog.": "点击查看更新日志。",
    "#adventure-chat channel.": "#adventure-chat 频道.",
    "all your progress will be lost.": "你所有的进度都会丢失。",
    "Degens Idle is much more mature and refined.": "Degens Idle更加成熟和精致。",
    "Discussion for this game is in the": "关于这个游戏的讨论是在",
    "Experience a deeper, more balanced strategy-based incremental game!": "体验更深入，更平衡的基于策略的增量游戏！",
    "feel free to support the developer!": "请随意支持开发人员！",
    "If you enjoy Prismatic Adventure and want to see more,": "如果你喜欢《棱柱冒险》，想看更多，",
    "It has undergone extensive revisions and community-driven optimizations,": "它经历了广泛的修订和社区驱动的优化，",
    "Learn the basics of gameplay, scaling, and tips to improve your efficiency.": "学习基本的游戏玩法，缩放和技巧，以提高你的效率。",
    "Load game progress from a file.": "从文件加载游戏进度。",
    "offering roughly 2 months of immersive gameplay,": "提供大约2个月的沉浸式游戏玩法，",
    "packed with surprises and robust prestige layers.": "充满惊喜和强大的声望层。",
    "Paste a save string from your clipboard to load progress.": "从剪贴板粘贴保存字符串以加载进度。",
    "Save your game progress to a file.": "将游戏进度保存到文件中。",
    "Save your game progress to the clipboard.": "将游戏进度保存到剪贴板。",
    "Since the only save mechanism is localStorage,": "由于唯一的保存机械是localStorage，",
    "This will overwrite your current progress.": "这将覆盖您当前的进度。",
    "View your achievements.": "查看你的成就。",
    "Warning: This will reset all game progress.": "警告：这将重置所有游戏进度。",
    "While Prismatic Adventure is still in its infancy,": "虽然《棱柱冒险》仍处于起步阶段，",
    "All resources only take effect after they are consumed": "所有资源只有被消耗后才会生效",
    "Magnifying Glass:": "放大镜:",
    "and last for all zones until a reset!": "并且所有区域持续到重置！",
    "Boosts Perception speed by 5%.": "提升5%的感知速度。",
    "Save copied to clipboard": "存档已保存到剪贴板",
    "Second Wind": "第二春",
    "After hitting critically low energy, get back up above starting energy.": "在达到临界低能量后，回到起始能量以上。",
    "As you progress, many layers of automation become available through perks and prestige upgrades, streamlining task management and resource usage. Basic automation options are to automate the Zone or to automate All, which will continue until no more automation is possible.": "随着你的进步，通过特权和声望升级，许多层次的自动化变得可用，简化任务管理和资源使用。基本的自动化选项是对区域进行自动化或对全部进行自动化，直到无法进行更多的自动化为止。",
    "Gold tasks are mandatory because they unlock travel to the next zone, while the green optional tasks allow you to choose the ones that best suit your strategy. Other task colors will be explained as you encounter them.": "黄金任务是强制性的，因为它们可以开启前往下一个区域的旅程，而绿色可选任务则允许你选择最适合自己策略的任务。其他任务颜色将在遇到它们时进行解释。",
    "Skills control two key factors: speed (how fast tasks progress) and energy drain (how much energy a task uses). Skill speed improves with level (at start, speed scales 1% per level while XP required scales 2% per level), and various resources, perks, and upgrades can further affect speed, energy drain, or XP scaling.": "技能控制着两个关键因素：速度（任务进展的速度）和能量消耗（任务消耗的能量）。技能速度随着等级的提升而提升（游戏邦注：一开始，速度每升1级增长1%，而经验值每升2级增长2%），各种资源、技能和升级会进一步影响速度、能量消耗或经验值的增长。",
    "Skills:": "技能:",
    "Automation:": "自动化:",
    "Tasks:": "任务:",
    "Resources:": "资源:",
    "Achievements:": "成就:",
    "Perks:": "特权:",
    "Close": "关闭",
    "Game Tips": "游戏提示",
    "You lose 50% of your resources (rounded up) on an energy reset. You can always freely use a resource if you have an even number of it. (for example: 4 Energy Elixirs = 2 after reset, 3 Energy Elixirs = 2 also after reset)": "你会在能量重置时损失50%的资源。如果你有偶数个资源，你总是可以自由使用它。（例如：重置后4能量药剂 = 2，重置后3能量药剂 = 2）",
    "Some tasks grant perks that persist through resets until you prestige. Tasks with perks that have not been unlocked yet are marked with a star. Some perks also have effects that you can toggle on or off.": "有些任务会给你额外的奖励，直到你获得声望。带有额外奖励的任务还没有被解锁，会被标记为星星。有些特殊待遇也有你可以打开或关闭的效果。",
    "Tasks are the actions you perform. You can start a task and pause it at any time—initially, only one task can run simultaneously. Tasks may use one, two, or three skills, with the speed and energy drain determined by multiplying the speed and drain multipliers from each selected skill. Hovering over a task (or holding on mobile) gives additional info. Note that the energy/time estimates are based on current skill levels - if a skill levels while performing the task then both energy and time will be less.": "任务是您执行的操作。您可以在任何时候启动和暂停任务——最初，只能同时运行一个任务。任务可以使用一个、两个或三个技能，速度和能量消耗取决于每个选择技能的速度和能量消耗乘数。将鼠标悬停在任务上（或在移动设备上）会提供额外的信息。注意，能量/时间估算是基于当前的技能水平——如果在执行任务时技能水平提高了，那么能量和时间都会减少。",
    "This game throws many mechanics at you - feel free to experiment by yourself, but this tutorial will walk you through the basics. As you progress, you'll discover that different stages of the game demand different strategies—what works in the early zones might not be as effective later on.\n      The complexity of resources and their interactions with skills, tasks, and resets scale up very quickly, so if you're looking for a chill, passive idle experience, this may not be the game for you.\n      Instead, be prepared to constantly adapt your strategy to optimize your resource management and efficiency.\n      And hey, if you manage to solve all the strategic puzzles and beat zone 33 with ease, send me your resume!": "这个游戏向你抛出了许多机械-你可以自由地自己尝试，但本教程将引导你完成基础知识。随着游戏的进展，你会发现游戏的不同阶段需要不同的策略——在早期有效的策略在之后可能就不那么有效了。\n      资源的复杂性以及它们与技能、任务和重置的相互作用会迅速扩大，所以如果你正在寻找一种冷静、被动的放置体验，那么这款游戏可能不适合你。\n      相反，要准备好不断调整策略以优化资源管理和效率。\n      嘿，如果你能解决所有的战略难题，轻松击败33区，把你的简历发给我！",
    "Some tasks produce resources. Resources must be consumed to take effect - nearly all effects last until you run out of energy or experience a copium/delusion reset. On an energy reset, you lose half of your resources.": "有些任务产生资源。资源必须消耗才能生效-几乎所有的效果都会持续到你耗尽能量或经历精神/妄想重置。在能量重置时，你会失去一半的资源。",
    "Tutorial & Tips": "教程 & 提示",
    "speed = baseSpeed * (perk 1) * (perk 2)...": "速度 = 基础速度 * (特权 1) * (特权 2)...",
    "speed = baseSpeed * (1 + sum(all resource boosts))": "速度 = 基础速度 * (1 + 总和(所有资源提升))",
    ".\n      Perks persist through energy, copium, and delusion resets. They do however get reset on prestige.": "。\ n福利坚持通过能源、精神，妄想重置。然而，他们的声望确实会被重置。",
    ". \n      The energy drain calculation is: ": "。\n能量消耗计算如下：",
    "Achievements are a one-and-done type of deal - once unlocked you have them forever. They provide a small speed boost to all skills (additive 1% per achievement).": "成就是一种一次性交易——一旦解锁，你就永远拥有它们。它们为所有技能提供了一个小的速度提升（每个成就增加1%）。",
    "Additional sections remain hidden until the corresponding mechanics are unlocked.": "在相应机械被解锁之前，其他部分将一直被隐藏。",
    "Alternate between \"Farm Runs\" (saving resources) and \"Push Runs\" (using both old and new resources for maximum progress).": "在“Farm Runs”（节省资源）和“Push Runs”（同时使用新旧资源以获得最大进度）之间交替进行。",
    "Don't dwell on completing everything in a zone. Often something in later zones will help a lot more.": "不要想着在一个区域内完成所有事情。通常在后面的区域会有更大的帮助。",
    "drain = baseDrain / (1 + sum(all resource boosts))": "消耗= 基础消耗 / （1 + 总计（所有资源提升））",
    "Hover over tasks, skills, resources, perks to view details about them.": "将鼠标悬停在任务、技能、资源和福利上，查看它们的详细信息。",
    "Keep in mind that energy requirements for tasks account for Energetic Bliss (when this perk is unlocked); when your energy drops below 80%, tasks may require more energy.": "请记住，任务的能量需求考虑到精力充沛的幸福（当这个特权被解锁时）；当你的能量低于80%时，任务可能需要更多的能量。",
    "Multi-skill tasks are generally better for grinding XP, especially tasks that use three skills.": "多技能任务通常更适合刷经验，特别是需要使用3种技能的任务。",
    "Once Energy Elixir cost is under 3 per task, it’s usually worth it to produce the max amount on every run.": "一旦每个任务的能量消耗低于3，那么在每次运行中产生最大的能量通常是值得的。",
    "Perk effects stack multiplicatively. If two different perks affect the speed of the same skill, the speed boost is calculated as:": "特权效果叠加成倍数。如果两种不同的技能影响同一技能的速度，速度提升的计算方法为：",
    "Resource boosts stack additively with themselves and with other resources. The skill speed calculation is: ": "资源提升与自身和其他资源叠加。技能速度计算如下：",
    "Source code is open so if you are interested in details of how formulas work, feel free to dive in and explore.": "源代码是开放的，所以如果您对公式如何工作的细节感兴趣，请随意潜入和探索。",
    "When the corresponding perk is unlocked, automation can be customized by toggling tasks on and off. This can be done by right clicking a task (or holding down on mobile).": "当相应的福利被解锁时，可以通过切换任务的开关来定制自动化。这可以通过右键单击任务（或按住手机）来完成。",
    "69 K?": "69 K?",
    "Advance to Zone 2.": "进入第2区。",
    "Advanced Potion Making without having seen any of those potions.": "进阶魔药制作，而不去看那些魔药。",
    "Amnesia": "失忆",
    "Apothecary": "药剂师",
    "Asymptote": "渐近线",
    "Attunement": "协调",
    "Baby Steps": "婴儿学步",
    "Big Game Hunter": "大型猎手",
    "Bookworm": "书呆子",
    "Certified Turtle": "认证海龟",
    "Click all the buttons on main settings page.": "点击主设置页面上的所有按钮。",
    "Complete your first Prestige.": "完成你的第一个威望",
    "Cool Little Brother": "酷小哥",
    "Copium reset with exactly 10 inifinity gauntlets and nothing else.": "精神重置时只有10个无限手套，仅此而已。",
    "Cybernetic Overload": "控制过载",
    "Defeat Agent Smith without using any resources.": "不使用任何资源击败 特工史密斯",
    "Defeat Big Brother after having only used sunglasses.": "在只使用太阳镜的情况下打败老大哥",
    "Defeat Chuck Norris after having used an energy core.": "在使用能量核心后击败查克·诺里斯",
    "Defeat Doctor Manhattan while holding atomic particle (unused).": "手持原子粒子击败曼哈顿博士（未使用）。",
    "Defeat Vegeta with 0 copium.": "使用 0 精神击败贝吉塔",
    "Delusion reset at over 50K delusion.": "妄想重置到超过50K妄想。",
    "Delusional": "妄想症",
    "Empty Pockets": "口袋空空",
    "Energy reset with over 8990 copium.": "能量重置超过8990精神。",
    "First Prestige": "第一声望",
    "Full clear Zone 3.": "完全清除区域3。",
    "Gain at least 69k serenity in one prestige.": "在一个威望中获得至少69k的宁静",
    "Gain over 100 starting energy from cybernetic implants in one run.": "在一次运行中从控制植入物中获得超过100的起始能量。",
    "Googolplex": "古戈尔普勒克斯",
    "Have at least 4 cybernetic armors left after energy reset.": "能量重置后至少有4件控制盔甲",
    "Hold over 200 Energy Elixirs in your inventory at once.": "一次在你的库存中持有超过200个能量酏剂。",
    "I'm Flying": "我在飞翔",
    "Instant Expert": "速成专家",
    "Jedi Master": "绝地大师",
    "Lose over 10K knowledge in a single copium reset.": "在一次精神重置中丢失超过10K的知识。",
    "Lucky": "幸运",
    "Mano a Mano": "短兵相接",
    "Mega Push": "超级推动",
    "Mondo Cool": "绝对的酷",
    "Not Delusional": "不是妄想",
    "Pause a boss fight.": "暂停boss战。",
    "Postpone Inevitable": "推迟不可避免",
    "Prestige 420 times.": "声望420次。",
    "Prestige with zone 7 being your best zone.": "在区域7声望是你最好的区域。",
    "Produce at least 14 resources at once.": "一次生产至少14种资源",
    "Reach your max delusion value exactly.": "正好达到你的最大妄想值。",
    "Reach zone 10 without using any resources and holding over 100 resources.": "在不使用任何资源的情况下到达10区，并且拥有超过100个资源。",
    "Reach zone 11 with zero energy resets.": "在零能量重置的情况下到达11区",
    "Reach Zone 15 without any resources (used or held).": "在没有任何资源（已使用或持有）的情况下到达区域15",
    "Rinnegan": "Rinnegan",
    "Seven": "七个",
    "Slay Godzilla without battling any previous bosses.": "在不与之前的boss战斗的情况下杀死哥斯拉。",
    "Stockpile": "储备",
    "Take a Breather": "休息一下",
    "Take down the Doctor": "干掉博士",
    "That Was Easy": "这很容易",
    "Toggle a perk to disable it.": "切换一个技能来禁用它。",
    "Toggler": "善变者",
    "Try to hold over 9 Googols in your inventory at once.": "尝试一次在你的库存中持有9个以上的 天文数字。",
    "Unlock the Master Ball.": "解锁大师球。",
    "Use cybernetic armor to make an energy elixir.": "使用控制盔甲制造能量药剂",
    "Use radiance when 2 unfinished tasks are above 90% complete.": "当2个未完成的任务完成超过90%时使用radiance。",
    "Use the power of Rinnegan.": "利用里尼根的力量。",
    "Using 1 lightsaber at a time, have it return 5 times in a row.": "一次使用一把光剑，让它连续返回5次。",
    "Wasted Armor": "浪费了盔甲",
    "What XP?": "什么经验？",
    "Stacks multiplicatively.": "堆叠相乘。",
    ", Intellect": "，智力",
    ": Rudimentary Upgrade": "：基本升级",
    ": Run City Marathon": "：跑城市马拉松",
    "Analyze traffic patterns using perception and intellect.": "使用感知和智力分析交通模式。",
    "Assemble Goggles": "组装护目镜",
    "Build yourself some eye protection.": "给自己做一些眼部保护。",
    "Construct a basic biomechanical upgrade.": "构建基本的生物机械升级。",
    "Enter Corporate District": "进入公司区",
    "Fix a Broken Engine": "修理坏了的引擎",
    "Learn the basics of machinery repair.": "学习机械维修的基本知识。",
    ", Intellect": "，智力",
    ", Tinkering": "，铸补",
    "Self-Operating Gadget: Simple Automation": "自动操作装置：简单的自动化",
    "Step into the orderly world of corporate business.": "步入公司业务的有序世界。",
    "Study Urban Traffic Flow": "城市交通流研究",
    "Test your stamina on a long city run.": "在城市长跑中测试你的耐力。",
    "Utilize your mechanical expertise and tinkering skills to build a basic automated system that streamlines routine tasks.": "利用你的机械专业知识和铸补技能来建立一个基本的自动化系统，简化日常任务。",
    ", Mechanics": "，机械",
    ": Finance Bro Advice": "：金融兄弟的建议",
    ": Mechanics of Luck": "：运气机械",
    "Advance to a high-tech cyber environment.": "向高科技网络环境迈进。",
    "Analyze corporate data with intellect and mechanics.": "运用智力和技巧分析公司数据。",
    "Automatically continue tasks until max reps.": "自动继续任务，直到最大的代表。",
    "Battle Agent Smith": "战斗特工史密斯",
    "Build a simple gacha machine.": "制作一台简单的gacha机器。",
    "Business Card Exchange": "交换名片",
    "Click to Toggle this perk.": "点击切换这个福利。",
    "Crunch Financial Numbers": "紧缩的财务数据",
    "Disabled Completionist.": "残疾的完美主义者。",
    "Don't worry, you can move to next zone without it.": "别担心，你可以不带它去下一个区域。",
    "Enabled Completionist.": "启用完成主义者。",
    "Endurance, Charisma, Perception": "耐力，魅力，洞察力",
    "Engage in simulated corporate conflicts.": "参与模拟的公司冲突。",
    "Learn how workaholics function.": "了解工作狂是如何工作的。",
    "Practice your charisma in a corporate setting.": "在公司环境中练习你的魅力。",
    "Proceed to Cyber Lab": "前往网络实验室",
    "Tactical Office Skirmish Simulation": "战术办公室小规模冲突模拟",
    "Take on this Matrix propagator. Might as well practice Combat.": "取这个矩阵传播子。不妨练习一下格斗。",
    "This button is red - it's a boss fight.": "这个按钮是红色的，这是一场boss战。",
    "OK": "确定",
    ": Study the Basics": "：学习基础知识",
    ": System Revamp": "：系统改造",
    "Battle Shao Kahn": "少卡恩之战",
    "Breach the Firewall": "突破防火墙",
    "Chemical Simulation": "化学模拟",
    "Crack the Cipher": "破解密码",
    "Create a simple amphetamine pill.": "制造一种简单的安非他明药片。",
    "Create an Amphetamine Pill": "制作安非他命药片",
    "Debug Digital Puzzle": "调试数字谜题",
    "Decrypt secret codes.": "解密密码。",
    ", Endurance": "，耐力",
    ", Mechanics": "，机械",
    ", Perception": "，感知",
    ", Tinkering, Intellect": "，铸补，智力",
    "Knowledge Unlocked!": "知识解锁!",
    "Learn basic system penetration.": "学习基本的系统渗透。",
    "Proceed to Combat Arena": "进入战斗竞技场",
    "Revamp a digital system to double its efficiency.": "改造数字系统，使其效率提高一倍。",
    "Simulate a chemical reaction.": "模拟化学反应。",
    "Solve a digital puzzle using coding skills.": "使用编码技巧解决一个数字谜题。",
    "Some clown challenges you to mortal combat.": "一些小丑向你发起致命的挑战。",
    "Step into the arena of combat.": "步入战斗的竞技场。",
    "Study the basics of hacking.": "学习入侵的基础知识。",
    "You now gain +0.1% XP per level for the following skills:": "你现在每等级获得+0.1%的经验为以下技能：",
    "All XP gains increased by 50%.": "所有经验增益增加50%。",
    "for tinkering, intellect, hacking.": "对于铸补，智力，入侵。",
    "Goggles:": "护目镜:",
    "Knowledge increases XP gain by": "知识增加经验增益",
    "That task is already completed.": "这个任务已经完成了。",
    "Energy is critically low!": "能量极低！",
    "Unlock ability to automate zones after fully completing 10 times.": "完全完成10次后解锁自动化区域的能力。",
    "Full Completes:": "完全完成:",
    "Automate:": "自动化:",
    "Zone": "区域",
    "Run all tasks in current zone.": "运行当前区域中的所有任务。",
    "Run all tasks in automated zones.": "运行自动化区域中的所有任务。",
    "Automation disabled": "自动化已禁用",
    "Automation ended.": "自动化已启用。",
    "Automation set to All mode": "自动化设置为所有模式",
    "Automation set to Zone mode": "自动化设置为区域模式",
    "25% chance to produce double resources.": "25%的几率产生双倍的资源。",
    "Sound Effects are recommended for boss fights. Just for fun!": "建议在Boss战斗中使用音效。只是为了好玩！",
    "Are you sure you want to FULL RESTART? This cannot be undone.": "你确定要重新开始吗？这是无法挽回的。",
    "Cancel": "取消",
    "Knowledge:": "知识:",
    "Knowledge increases your XP gain for related skills. It is earned from tasks that use knowledge-based skills and is crucial for fast leveling and overall progress. Note that knowledge is only gained after completing all repetitions of a task.": "知识可以增加相关技能的经验值。它可以从使用知识技能的任务中获得，对于快速升级和整体进展至关重要。请注意，只有在完成所有重复的任务后才能获得知识。",
    "Load this save? (Page will refresh after loading)": "是否加载此存档？（页面加载后会刷新）",
    "Use All": "使用全部",
    "Use One": "使用1个",
    " is active!": " 已激活！",
    "Allows running two tasks simultaneously.": "允许同时运行两个任务。",
    "But you will permanently gain 6 starting energy.": "但你将永久获得6个起始能量。",
    "Copium builds up from tasks with": "精神从任务中积累起来",
    "endurance, alchemy, mechanics.": "耐力，炼金术，机械。",
    "for combat, endurance.": "对于战斗，耐力。",
    "If it exceeds 9000, your game will reset": "如果超过9000，你的游戏将重置",
    "Increase starting Energy gained for each Copium reset to +6.": "每重置一次精神所获得的起始能量为+6。",
    "Power increases speed by": "力量增加速度",
    "Reduce Hacking energy drain by 10%.": "减少10%的入侵能量消耗。",
    "While energy is above 80%, task progress is doubled.": "当能量超过80%时，任务进度翻倍。",
    "with all Resources and half your Knowledge lost!": "失去了所有的资源和一半的知识！",
    "Agent Smith defeated! +1 Power": "史密斯探员被打败了！+ 1力量",
    "Amphetamine Pill:": "安非他命药丸:",
    "And Makes you look cool.": "让你看起来很酷。",
    "Cool Sunglasses:": "酷的太阳镜:",
    "Reduces Endurance and Combat energy drain by 10%.": "减少10%的耐力和战斗能量消耗。",
    "Reduces Hacking energy drain by 100%.": "减少100%的攻击能量消耗。",
    "Reduces Tinkering and Hacking energy drain by 5%.": "减少铸补和入侵 5% 的能量消耗。",
    "Steroids:": "类固醇:",
    ", Intellect": "智力",
    ", Quantum": "，量子",
    ", Charisma": "，魅力",
    ", Endurance, Perception": "，耐力，感知",
    ", Hacking": "，入侵",
    ": Find a Tool": "：找一个工具",
    ": Painstaking Training": "：艰苦的训练",
    ": Synthesize a Contraption": "：合成一个精巧装置",
    ": Talk Your Way": "：用你的方式说话",
    "Battle Sauron": "索伦之战",
    "Calibrate cybernetic systems.": "校准控制系统。",
    "Challenge Dojo Master Chuck Norris": "挑战道场大师查克·诺里斯",
    "Challenge the legendary martial artist.": "挑战传奇武术家。",
    "Climb to the city rooftop.": "爬上城市的屋顶。",
    "Concoct Some Steroids": "调制一些类固醇",
    "Convince the masters to help you improve your learning.": "说服大师帮助你提高你的学习。",
    "Create a contraption using advanced techniques.": "使用先进的技术创建一个精巧的装置。",
    "Create a performance-enhancing steroid.": "制造一种提高成绩的类固醇。",
    "Descend deeper into the digital realm.": "深入到数字领域。",
    "Develop team-based combat strategies.": "开发基于团队的战斗策略。",
    "Endurance, Alchemy, Mechanics": "耐力，炼金术，机械",
    "Engage in a grueling training session.": "参加艰苦的训练课程。",
    "Exosuit Upgrade Overhaul": "外衣升级大修",
    "Learn the fundamentals of combat.": "学习战斗的基本原理。",
    "Locate a futuristic wrench.": "找到一个未来的扳手。",
    "Navigate to Abandoned Factory": "前往废弃工厂",
    "Neural Implant Test": "神经植入试验",
    "Practice with simulated weapons.": "使用模拟武器进行练习。",
    "Proceed to Rooftop Rendezvous": "前往天台会合",
    "Save Some Touchable Grass": "保存一些可触摸的草",
    "Simulated Weapon Drills": "模拟武器演习",
    "Sparring Session": "切磋环节",
    "Spot touchable grass and pick some for later.": "找到可触摸的草，摘一些供以后使用。",
    "System Calibration Diagnostic Run": "系统校准诊断运行",
    "Tactical Group Skirmish": "战术群战",
    "Take on the creator of just one ring.": "和一个戒指的创造者较量一下。",
    "Test cutting-edge neural implants.": "测试尖端的神经植入物。",
    "Upgrade your cybernetic exosuit.": "升级你的控制服。",
    "It's over 9000! Your copium that is.": "超过9000了！那是你的精神。",
    "You lose all your resources and half your knowledge.": "你失去了所有的资源和一半的知识。",
    "Copium builds up from tasks that use copium-related skills, and reaching max copium will reset the game. Keep in mind that copium can be used to your advantage. Later in the game, strategies utilizing copium become essential.": "精神是通过使用精神相关技能的任务而建立起来的，达到最大精神将重置游戏。记住，精神可以为你所用。在游戏后期，利用精神的策略变得至关重要。",
    "Power:": "力量:",
    "Copium:": "精神:",
    "Power boosts the speed of power-related tasks (initially Combat and Endurance) and is obtained by defeating bosses.": "力量可以提高力量相关任务的速度（最初是战斗和耐力），并通过击败Boss获得。",
    " drains 3x less energy.": "消耗能量减少3倍。",
    " to the forsaken bastion.": "去被遗忘的堡垒。",
    ", Quantum": "，量子",
    ": Energy Galore": "：能源丰富",
    ": Haggle for it": "：讨价还价",
    "25x increased charisma XP gain.": "增加25倍魅力经验值。",
    "5x increased AI Mastery XP gain.": "AI精通经验增加5倍。",
    "7% chance to produce 7x resources.": "7%的机会生产7x资源。",
    "A high-tech take on social engineering.": "一个高科技的社会工程。",
    "Algorithm Optimization": "算法优化",
    "All XP gains increased by 28%.": "所有经验值增加28%。",
    "And decrease Charisma energy drain by 28%.": "减少28%的魅力能量消耗。",
    "And makes you look more shiny.": "让你看起来更有光泽。",
    "Any task ending or pausing task will remove the armor.": "任何任务结束或暂停都会移除盔甲。",
    "Attempt to create a sentient crystal.": "尝试创造一个有知觉的水晶。",
    "Create a quantum vitalizer for health benefits.": "为健康创造一种量子活力剂。",
    "Cybernetic Armor:": "控制盔甲：",
    "Deplot Cyber Barrier": "部署网络屏障",
    "Deploy a robust digital defense.": "部署强大的数字防御。",
    "Experiment with quantum particles.": "用量子粒子做实验。",
    "Find a map to the forsaken bastion.": "找到一张去被遗忘堡垒的地图。",
    "Find Map to Forsaken Bastion": "找到去被遗忘堡垒的地图",
    "Haggle with a science nerd.": "和一个科学迷讨价还价。",
    "Hyperlink Manipulation": "超链接操作",
    "Improves automation to allow selecting individual tasks.": "改进自动化，允许选择单独的任务。",
    "Increase travel speed by 4x.": "使行进速度提高4倍。",
    "Multiple uses stack with # of tasks, not with drain.": "多重使用堆栈与#的任务，而不是与drain。",
    "Proceed to Forsaken Bastion": "前往被遗忘堡垒",
    "Random Crystal: Sentience Attempt": "随机水晶：感知尝试",
    "Reduce Copium gain by 60%.": "减少60%精神的增益。",
    "Reduce minimum energy drain by 75%.": "减少75%的最小能量消耗。",
    "Reduces Combat energy drain by 100%.": "减少战斗能量消耗100%。",
    "Reduces energy drain by 75% for next task (one square).": "为下一个任务减少75%的能量消耗（一个方格）。",
    "Refine and optimize complex algorithms.": "完善和优化复杂的算法。",
    "Right click a task to toggle automation.": "右键单击任务以切换自动化。",
    "Shiny Helmet:": "闪亮头盔：",
    "Subatomic Experiment": "亚原子实验",
    "This affects tasks that are completed in one tick.": "这会影响在一个tick内完成的任务。",
    " Vitalizer: Energy Galore": "活力：能量充沛",
    ", AiMastery": "， Ai精通",
    ", Combat": "，战斗",
    ", Cybernetics": "，控制",
    ": Adopt a Dog": "：领养一只狗",
    ": Decent Algorithm": "：体面的算法",
    ": Find the Clover": "：找到三叶草",
    ": Steal One": "：偷一个",
    ": Ultimate Feat of Engineering": "工程的终极壮举",
    "Adopt a loyal dog.": "领养一只忠诚的狗。",
    "Battle Isshin": "伊信之战",
    "Battle Kratos": "奎托斯之战",
    "Broker a Tactical Deal": "撮合一笔策略性交易",
    "Carefully craft a cybernetic armor.": "精心制作一件控制盔甲。",
    "Challenge the demi-god.": "挑战半神。",
    "Challenge the master of the blade.": "向剑术大师挑战。",
    "Climb out to the bustling Techno District.": "爬到熙熙攘攘的科技区。",
    "Copius Alchemist: Advanced Manual": "科皮乌斯炼金术士：高级手册",
    "Create a cybernetic potion.": "创造一种控制药水。",
    "Create the ultimate feat of engineering.": "创造工程学的终极壮举。",
    "Cybernetic Armor": "控制盔甲",
    "Cybernetic Potion": "控制药水",
    "Cybernetic Potion:": "控制药水：",
    "Descend to Digital Underground": "进入数码地下",
    "Digital Data Frenzy Challenge": "数字数据狂潮挑战",
    "Emerge into Techno District": "进入科技区",
    "Engage in simulated digital battles.": "参与模拟的数字战斗。",
    "Enhance and optimize neural networks.": "增强和优化神经网络。",
    "Extract and decode hidden data.": "提取和解码隐藏的数据。",
    "Extract Encrypted Secrets": "提取加密的秘密",
    "Head back into the digital depths.": "回到数字世界的深处。",
    "Head to the hub of advanced AI research.": "前往高级人工智能研究中心。",
    "Hone your negotiation skills in high places.": "在高处磨练你的谈判技巧。",
    "Leverage AI to create a cybernetic combat enhancement.": "利用AI创造一个控制的战斗增强。",
    "Locate a lucky clover.": "找到幸运的三叶草。",
    "Omega Resonator: Cybernetic Enhancement": "欧米茄共振器：控制增强",
    "Optimize the Neural Net System": "优化神经网络系统",
    "Override the Grid": "覆盖网格",
    "Persuade the High-Rise Crowd": "说服高层人士",
    "Process rapid streams of digital data.": "处理快速的数字数据流。",
    "Reduced Combat energy drain by 100%.": "减少战斗能量消耗100%。",
    "Reduced Cybernetics energy drain by 260%.": "减少控制能量消耗260%。",
    "Reduced energy drain by 75% for next 2 tasks": "在接下来的2个任务中减少75%的能量消耗",
    "Reduces Cybernetics energy drain by 20%.": "减少控制能量消耗20%。",
    "Run selected tasks in automated zones.": "在自动化区域中运行选定的任务。",
    "Run selected tasks in current zone.": "运行当前分区中选定的任务。",
    "Steal a hoverboard for high-speed travel.": "偷一个悬浮滑板来进行高速旅行。",
    "Study advanced alchemical techniques.": "学习先进的炼金术。",
    "Take control of the city's digital infrastructure.": "控制城市的数字基础设施。",
    "Tinkering, Cybernetics": "铸补，控制",
    "Tinkering, Cybernetics, Hacking": "铸补，控制，入侵",
    "Train a reinforcement learning algorithm.": "训练一个强化学习算法。",
    "Use your wit to sway opinions.": "用你的智慧来左右别人的意见。",
    "Venture to Research Facility": "投资研究设施",
    "Virtual Simulated Skirmish": "虚拟模拟战斗",
    " Training": "训练",
    " Vitalizer:": "活力剂：",
    ", Negotiation": "，谈判",
    ": Guerrilla Warfare Sprint": "：游击战冲刺",
    ": Knowledge Expansion": "：知识拓展",
    ": New Invention": "：新发明",
    ": System Repair": "：系统维修",
    "Approach a dazzling metropolis of the future.": "接近一个耀眼的未来大都市。",
    "Battle Deadpool": "死侍之战",
    "Battle Vegeta": "贝吉塔之战",
    "Beg for Ascension": "祈求转生",
    "Boosted Combat speed by 240%.": "战斗速度提高240%",
    "Boosts Combat speed by 20%.": "提高20%的战斗速度。",
    "Breach a secure digital vault.": "破坏一个安全的数字保险库。",
    "Breach an enemy outpost undetected.": "潜入敌人的前哨而不被发现。",
    "Challenge the merc with a mouth.": "用嘴挑战雇佣兵。",
    "Challenge the prince of all Saiyans.": "挑战所有赛亚人的王子。",
    "charisma, perception, aiMastery, negotiation.": "魅力，感知，AI精通，谈判。",
    "Convince ascended beings to let you access their metropolis.": "说服扬升生物让你进入他们的大都市。",
    "Create a machine that preserves knowledge.": "创造一台保存知识的机器。",
    "Create a potion that cleanses the mind.": "创造一种净化心灵的药剂。",
    "Delusion builds up from tasks with": "妄想是由任务产生的",
    "Endurance, Combat": "耐力，战斗",
    "Ex: energy reset on zone 8 gives +0.8 starting energy.": "例如：能量重置在区域8给予+0.8开始能量。",
    "Exit to Shattered Expanse": "出口到破碎苍穹",
    "Expand your knowledge of mechanics.": "扩展你的力学知识。",
    "Gain Zone / 10 starting Energy for each Energy reset.": "每重置一次能量，获得10个起始能量。",
    "High-Intensity Bunker Blitz Drill": "高强度地堡闪电战演习",
    "Infuse a Sanity Cleanser": "注入健康清洁剂",
    "Journey back to the shattered expanse.": "回到破碎苍穹。",
    "Journey to Exalting Metropolis": "提升大都会之旅",
    "Knowledge also levels with and boosts Mechanics.": "知识也能够提升机制。",
    "Levels up a random skill to next level.": "将随机技能升级到下一个级别。",
    "Omega Resonator:": "欧米伽共鸣器：",
    "Produce Augment Fuel": "生产补充燃料",
    "Push your endurance to the limit in a confined space.": "在有限的空间里把你的耐力推到极限。",
    "Random Crystal:": "随机水晶:",
    "Reduce all skill XP scaling from 2% to 1.9%.": "减少所有技能经验从2%到1.9%。",
    "Reduce Knowledge loss on copium reset by 80%.": "减少量子重置时80%的知识损失。",
    "Reduce Quantum energy drain by 40%.": "减少量子能量消耗40%。",
    "Repair and optimize atomic systems.": "修复和优化原子系统。",
    "Secure Vault Access Code Breaker": "安全保险库访问破码器",
    "Silent Outpost Infiltration": "无声前哨渗透",
    "Sprint through a raging sandstorm.": "在肆虐的沙尘暴中冲刺。",
    "Synethesize some augment fuel.": "合成一些增强燃料。",
    "Tinkering, Intellect": "修补，智力",
    "Tinkering, Intellect, Mechanics": "铸补，智力，力学",
    "Train for long-distance travel.": "长途旅行的训练。",
    "with 20% of your Power lost!": "失去了20%的能量！",
    "with all Resources and 10% of your Knowledge lost!": "失去所有的资源和10%的知识！",
    "You lose all your resources and 10% of your knowledge.": "你失去了所有的资源和10%的知识。",
    "Delusion, like copium, builds up through tasks using delusion-related skills and reaching max will reset the game. Throughout the game, more delusion-related features will unlock, and keeping it balanced will be very beneficial. Though initially it may seem only negative, a delusion reset causes no resource loss, which can help build powerful runs.": "妄想，就像copium，通过使用妄想相关技能的任务来建立，达到最大值将重置游戏。在整个游戏过程中，更多与妄想相关的功能将被解锁，保持平衡将是非常有益的。虽然一开始它可能看起来只是消极的，但妄想重置不会造成资源损失，这有助于构建强大的运行。",
    "And reduces Negotiation energy drain by 100%.": "并减少谈判能量消耗100%。",
    "Boosts Charisma speed by 25%.": "使魅力速度提高25%。",
    "By letting them know you are a ninja.": "让他们知道你是忍者。",
    "Delusion:": "妄想：",
    "Dojo Master Chuck Norris defeated! +3 Power": "道场大师查克·诺里斯被打败了！+ 3力量",
    "for tinkering, intellect, hacking, mechanics.": "为了铸补，智力，黑客，机制。",
    "Karate Belt:": "空手道腰带:",
    "Sauron defeated! +4 Power": "索伦被打败了！+ 4力量",
    "Shao Kahn defeated! +2 Power": "少卡恩已被击败！+ 2力量",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Zone 13: Shattered Expanse": "区域13：破碎苍穹",
    "Zone 12: Forsaken Bastion": "区域12：被遗忘的堡垒",
    "Zone 10: Techno District": "区域10：科技区",
    "Zone 8: Rooftop Rendezvous": "区域8：天台汇合",
    "Zone 9: Digital Underground": "区域9：数字地下",
    "Zone 11: Research Facility": "区域11：研究设施",
    "Zone 7: Abandoned Factory": "区域7：废弃工厂",
    "Zone 6: Combat Arena": "区域6：战斗竞技场",
    "Zone 5: Cyber Lab": "区域5: 网络实验室",
    "Zone 4: Corporate District": "区域4: 公司区域",
    "Zone 3: City Core": "区域3: 城市核心",
    "Zone 2: Urban Outskirts": "区域2: 城市郊区",
    "Zone 1: Beginner’s Bootcamp": "区域1: 初学者训练营",
    "Kuzzi Games Discord": "Kuzzi Games Discord",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "★": "★",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Energy Drain: ": "能量消耗:",
    "Copium Reactor": "精神反应堆",
    "Travel: ": "旅行: ",
    "Speed: ": "速度: ",
    "Tinkering": "铸补",
    "XP: ": "经验值: ",
    "Estimated Time: ": "预计时间：",
    "Estimated Time for next task: ": "下次任务预计时间：",
    "Endurance": "耐力",
    "Uses: ": "使用: ",
    "Basic Mech": "基本机械",
    "Brewmaster": "酿酒师",
    "Celestial Light": "天光",
    "Completionist": "完美主义者",
    "Copious Alchemist": "丰富的炼金术士",
    "Crypto Wallet": "加密钱包",
    "Cyber Boost": "赛博加成",
    "Digital Dreams": "数字梦想",
    "Dimension Mastery": "次元精通",
    "Double Timer": "双计时器",
    "Echo Of Nothing": "无物回响",
    "Energetic Bliss": "元气极乐",
    "Expanse Echo": "苍穹回声",
    "Forge Fervor": "锻造激情",
    "Four Leaf Clover": "四叶草",
    "Futuristic Wrench": "未来扳手",
    "Gacha Machine": "扭蛋机",
    "Growth Miracle": "生长奇迹",
    "Healthy Living": "健康生活",
    "Hoverboard": "悬浮滑板",
    "Immunity Device": "免疫装置",
    "Inspired Glow": "激发辉光",
    "Knowledge Preserver": "知识守护者",
    "Kung Fu Zen": "功夫禅宗",
    "Last Stand": "最后一站",
    "Master Of Ai": "Ai大师",
    "Mechanical Genius": "机械天才",
    "Neon Energy": "霓虹能量",
    "Neural Matrix": "神经矩阵",
    "Nihilistic Beats": "虚无的节拍",
    "Noob Haxor": "新手Haxor",
    "Omega Stability": "欧米伽稳定性",
    " Harmony": "和声",
    " Teleportation": "传送",
    " Vitalizer": "激活器",
    "Reinforcement Learning": "强化学习",
    "Rex": "国王",
    "Perception": "感知",
    "Intellect": "智力",
    "Sandstorm": "沙尘暴",
    "Self Operating Gadget": "自动操作装置",
    "Simulation Engine": "模拟引擎",
    "Spark Of Infinity": "无限火花",
    "Spectral Glow": "光谱辉光",
    "Stellar Dreams": "星辰之梦",
    "Time Glimpse": "时光一瞥",
    "Universal Alloy": "通用合金",
    "Urban Warfare": "城市战争",
    "Wise Mechanic": "明智的机械师",
    "Workaholic": "工作狂",
    "Task XP Multiplier: ": "任务经验乘数: ",
    "Charisma": "魅力",
    "Alchemy": "炼金术",
    "Travel": "旅行",
    "Boosted Perception by ": "感知提升 ",
    "Achievement: ": "成就: ",
    "(Task Progress Mult: ": "(任务进度乘数: ",
    "Energy: ": "能量: ",
    "Energy drains based on each skill used.": "能量消耗取决于所使用的技能。",
    "Task Speed Multiplier: ": "任务速度乘数: ",
    "Task Drain Multiplier: ": "任务消耗乘数: ",
    "Mechanics": "机械",
    "Knowledge Gain on Completion: ": "完成后的知识增益: ",
    "Hacking": "入侵",
    "Combat": "战斗",
    "Reduce all energy drain by ": "减少所有能量消耗 ",
    "Reduces Alchemy energy drain by ": "减少炼金术的能量消耗",
    "Increases starting Energy by ": "增加初始能量 ",
    "Cybernetics": "控制",
    "Negotiation": "谈判",
    "Copium Gain for next Task: ": "下一个任务的精神增益：",
    "Power Gain on Completion: ": "完成时力量增益：",
    "Reduced Alchemy energy drain by ": "减少炼金术的能量消耗 ",
    "Reduced Hacking energy drain by ": "减少入侵的能量消耗 ",
    "Reduced Tinkering and Hacking energy drain by ": "减少铸补和入侵的能量消耗 ",
    "AiMastery": "Ai精通",
    "Quantum": "量子",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    " (Level: ": " (等级: ",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " unlocked": " 已解锁",
    "% of a level": "% 的等级",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\%.$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)B \/ ([\d\.]+)B$/,
    /^([\d\.]+)T \/ ([\d\.]+)T$/,
    /^([\d\.]+)B \/ ([\d\.]+)T$/,
    /^([\d\.]+)M \/ ([\d\.]+)M$/,
    /^([\d\.]+)K \/ ([\d\.]+)K$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)\)$/,
    /^x([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+) tick$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Delusion Gain for next Task: (.+) \(random, skewed to low\)$/, '下一个任务的妄想增益：$1（随机，偏低）'],
    [/^Zone (.+) completed (.+) times.$/, '区域 $1 完成 $2 次.'],
    [/^New best fully compeleted: Zone (.+) with (.+) resets$/, '全新最佳完成：区域 $1 重置 $2 次'],
    [/^: (.+) of a level$/, ': 一级的 $1'],
    [/^But you permanently gain (.+) starting energy.$/, '但你会永久获得 $1 初始能量。'],
    [/^This is your (.+) Copium reset.$/, '这是你的第 $1 次精神重置。'],
    [/^This is your (.+) Energy reset.$/, '这是你的第 $1 次能量重置。'],
    [/^Click to gain (.+) Energy.$/, '点击获得 $1 能量。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Version: ([\d\.]+)$/, '版本: $1'],
    [/^([\d\.]+) s$/, '$1 秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+) m ([\d\.]+) s$/, '$1 分 $2 秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^ \(Level: ([\d\.,]+)\)$/, ' (等级: $1)'],
    [/^ \+([\d\.,]+) \(Level: ([\d\.,]+)\)$/, ' \+$2 (等级: $2)'],
    [/^ \+([\d\.,]+) \(Level: ([\d\.,]+)\).$/, ' \+$2 (等级: $2).'],
    [/^: Unlock perk on Zone ([\d\.,]+).$/, '：解锁区域 $1 的特权。'],
    [/^\+([\d\.,]+) levels$/, '\+$1 等级'],
    [/^\+([\d\.,]+) level$/, '\+$1 等级'],
    [/^(.+)leveled up to ([\d\.,]+)$/, '$1 升级到了 $2'],
    [/^Gained ([\d\.,]+) Energy.$/, '获得 $1 能量。'],
    [/^Used ([\d\.,]+) Random Crystals. Leveled up:$/, '使用了 $1 随机晶体。升级：'],
    [/^Used ([\d\.,]+) Goggles.$/, '使用了 $1 护目镜。'],
    [/^Used ([\d\.,]+) Omega Resonators.$/, '使用了 $1 欧米伽谐振器。'],
    [/^Used ([\d\.,]+) Cybernetic Potions.$/, '使用了 $1 控制药水。'],
    [/^Used ([\d\.,]+) Cybernetic Armors.$/, '使用了 $1 控制盔甲。'],
    [/^Used ([\d\.,]+) Shiny Helmet.$/, '使用了 $1 闪亮头盔。'],
    [/^Used ([\d\.,]+) Amphetamine Pills.$/, '使用了 $1 安非他命药丸。'],
    [/^Used ([\d\.,]+) Cool Sunglasses.$/, '使用了 $1 酷的太阳镜。'],
    [/^Used ([\d\.,]+) Energy Elixir.$/, '使用了 $1 能量药剂。'],
    [/^Used ([\d\.,]+) Energy Elixirs.$/, '使用了 $1 能量药剂。'],
    [/^Used ([\d\.,]+) Magnifying Glass.$/, '使用了 $1 放大镜。'],
    [/^Used ([\d\.,]+) Magnifying Glasses.$/, '使用了 $1 放大镜。'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);