/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Alchemy:": "炼金术:",
    "Energy": "能量",
    "Copium": "精神",
    "Power": "力量",
    "Perks": "特权",
    "Travel:": "旅行：",
    "Resources": "资源",
    "Serenity": "宁静",
    "Knowledge": "知识",
    "Mirror Mojo": "镜子魔咒",
    "Delusion": "妄想",
    "Assemble a Clockwork Toy": "组装一个发条玩具",
    "Brew a Simple Potion": "酿造一个简单的药水",
    "Combined Assembly Drill": "组合钻机",
    "Estimated Levels Gained:": "预计获得等级：",
    "Small Talk Practice": "闲聊练习",
    "Exit Bootcamp": "退出训练营",
    "of this task will produce a resource.": "这个任务将产生一个资源。",
    "Warm-Up Jog in Place": "原地慢跑热身",
    "Endurance, Tinkering": "耐力，铸补",
    "Tinkering, Charisma": "铸补，魅力",
    "The dark green button indicates travel to the next zone.": "深绿色按钮表示前往下一个区域。",
    "The resource icon indicates that each completion": "资源图标表示每次完成",
    "Brewmaster: Read an Alchemy Book": "酿酒大师：读一本炼金术方面的书",
    "Experiment with ingredients to create a potion.": "试着用各种原料制作一种药剂。",
    "Leave bootcamp and begin your journey.": "离开训练营，开始你的旅程。",
    "Estimated Energy Needed for next task:": "预计下一任务所需能量：",
    "Estimated Energy Needed:": "预计所需能量：",
    "Estimated Levels Gained for next task:": "下一任务预计获得等级：",
    ": Read an Alchemy Book": "：阅读一本炼金书",
    "Tinkering": "铸补",
    "A challenging drill combining physical": "结合物理训练的具有挑战性的训练",
    "Boost your stamina with a simple jog.": "通过简单的慢跑来增强你的耐力。",
    "Endurance": "耐力",
    "for the first time will grant a perk.": "这将是第一次给予特权。",
    "mandatory to progress to next zone.": "必须进入下一个区域。",
    "Polish your social skills with casual chat.": "通过随意的聊天来提高你的社交技巧。",
    "Practice assembling basic mechanisms.": "练习组装基本机构。",
    "stamina and careful assembly.": "耐力和细心组装。",
    "Study the ancient art of alchemy.": "学习古老的炼金术。",
    "The orange button indicates that this task is": "橙色按钮表示该任务是",
    "Tinker with your mirror while engaging in charismatic banter.": "一边摆弄镜子，一边和别人开玩笑。",
    "You cannot start another task right now": "你现在不能开始另一项任务",
    "The ★ indicates that completing this task": "★ 表示完成此任务",
    "Game Over": "游戏结束",
    "Restart": "重新开始",
    "This is your 1st Energy reset.": "这是你的第 1 次能量重置。",
    "You lose half your resources.": "你失去了一半的资源。",
    "You ran out of energy.": "你的能量耗尽了。",
    "Energy Elixir:": "能量药剂：",
    "Right-click to consume all.": "右键点击以消耗全部。",
    "This is your 2nd Energy reset.": "这是你的第 2 次能量重置。",
    "This is your 3rd Energy reset.": "这是你的第 3 次能量重置。",
    " unlocked!": " 已解锁!",
    " is 25% faster.": " 变快 25%。",
    ": Explore Dietary Options": "：探索饮食选择",
    "Assemble a Magnifying Glass": "组装一个放大镜",
    "Assemble a simple magnifying glass.": "组装一个简单的放大镜。",
    "Combined Recall Drill": "联合回忆练习",
    "Endurance, Intellect": "耐力，智力",
    "Endurance, Intellect, Alchemy": "耐力，智力，炼金术",
    "Engage strangers in conversation.": "与陌生人交谈。",
    "Head to the City Core": "前往市中心",
    "Intellect:": "智力:",
    "Learn about healthy eating habits.": "学习健康的饮食习惯。",
    "Map the City": "绘制城市地图",
    "Perception:": "感知：",
    "Sharpen your senses by noticing urban subtleties.": "通过观察城市的细微之处来增强你的感官。",
    "Spot Architectural Details": "发现建筑细节",
    "Strike up a Quick Chat": "开始快速聊天",
    "Run while recalling facts about your surroundings.": "一边跑步一边回忆周围的事情。",
    "Study the city’s layout to boost your intellect.": "研究城市的布局来提高你的智力。",
    "Venture into the bustling heart of the city.": "冒险进入繁华的市中心。",
    "Try": "试试",
    "Copy": "复制",
    "Back": "返回",
    "Degens Idle": "Degens放置",
    "Load": "加载",
    "Paste": "粘贴",
    "Music": "音乐",
    "Sound Effects": "音效",
    "Volume:": "音量:",
    "Tutorial": "教程",
    "Full Restart": "完全重新开始",
    "Buy Me a Coffee": "请作者喝杯咖啡",
    "Click to see changelog.": "点击查看更新日志。",
    "#adventure-chat channel.": "#adventure-chat 频道.",
    "all your progress will be lost.": "你所有的进度都会丢失。",
    "Degens Idle is much more mature and refined.": "Degens Idle更加成熟和精致。",
    "Discussion for this game is in the": "关于这个游戏的讨论是在",
    "Experience a deeper, more balanced strategy-based incremental game!": "体验更深入，更平衡的基于策略的增量游戏！",
    "feel free to support the developer!": "请随意支持开发人员！",
    "If you enjoy Prismatic Adventure and want to see more,": "如果你喜欢《棱柱冒险》，想看更多，",
    "It has undergone extensive revisions and community-driven optimizations,": "它经历了广泛的修订和社区驱动的优化，",
    "Learn the basics of gameplay, scaling, and tips to improve your efficiency.": "学习基本的游戏玩法，缩放和技巧，以提高你的效率。",
    "Load game progress from a file.": "从文件加载游戏进度。",
    "offering roughly 2 months of immersive gameplay,": "提供大约2个月的沉浸式游戏玩法，",
    "packed with surprises and robust prestige layers.": "充满惊喜和强大的声望层。",
    "Paste a save string from your clipboard to load progress.": "从剪贴板粘贴保存字符串以加载进度。",
    "Save your game progress to a file.": "将游戏进度保存到文件中。",
    "Save your game progress to the clipboard.": "将游戏进度保存到剪贴板。",
    "Since the only save mechanism is localStorage,": "由于唯一的保存机械是localStorage，",
    "This will overwrite your current progress.": "这将覆盖您当前的进度。",
    "View your achievements.": "查看你的成就。",
    "Warning: This will reset all game progress.": "警告：这将重置所有游戏进度。",
    "While Prismatic Adventure is still in its infancy,": "虽然《棱柱冒险》仍处于起步阶段，",
    "All resources only take effect after they are consumed": "所有资源只有被消耗后才会生效",
    "Magnifying Glass:": "放大镜:",
    "and last for all zones until a reset!": "并且所有区域持续到重置！",
    "Boosts Perception speed by 5%.": "提升5%的感知速度。",
    "Save copied to clipboard": "存档已保存到剪贴板",
    "Second Wind": "第二春",
    "After hitting critically low energy, get back up above starting energy.": "在达到临界低能量后，回到起始能量以上。",
    "As you progress, many layers of automation become available through perks and prestige upgrades, streamlining task management and resource usage. Basic automation options are to automate the Zone or to automate All, which will continue until no more automation is possible.": "随着你的进步，通过特权和声望升级，许多层次的自动化变得可用，简化任务管理和资源使用。基本的自动化选项是对区域进行自动化或对全部进行自动化，直到无法进行更多的自动化为止。",
    "Gold tasks are mandatory because they unlock travel to the next zone, while the green optional tasks allow you to choose the ones that best suit your strategy. Other task colors will be explained as you encounter them.": "黄金任务是强制性的，因为它们可以开启前往下一个区域的旅程，而绿色可选任务则允许你选择最适合自己策略的任务。其他任务颜色将在遇到它们时进行解释。",
    "Skills control two key factors: speed (how fast tasks progress) and energy drain (how much energy a task uses). Skill speed improves with level (at start, speed scales 1% per level while XP required scales 2% per level), and various resources, perks, and upgrades can further affect speed, energy drain, or XP scaling.": "技能控制着两个关键因素：速度（任务进展的速度）和能量消耗（任务消耗的能量）。技能速度随着等级的提升而提升（游戏邦注：一开始，速度每升1级增长1%，而经验值每升2级增长2%），各种资源、技能和升级会进一步影响速度、能量消耗或经验值的增长。",
    "Skills:": "技能:",
    "Automation:": "自动化:",
    "Tasks:": "任务:",
    "Resources:": "资源:",
    "Achievements:": "成就:",
    "Perks:": "特权:",
    "Close": "关闭",
    "Game Tips": "游戏提示",
    "You lose 50% of your resources (rounded up) on an energy reset. You can always freely use a resource if you have an even number of it. (for example: 4 Energy Elixirs = 2 after reset, 3 Energy Elixirs = 2 also after reset)": "你会在能量重置时损失50%的资源。如果你有偶数个资源，你总是可以自由使用它。（例如：重置后4能量药剂 = 2，重置后3能量药剂 = 2）",
    "Some tasks grant perks that persist through resets until you prestige. Tasks with perks that have not been unlocked yet are marked with a star. Some perks also have effects that you can toggle on or off.": "有些任务会给你额外的奖励，直到你获得声望。带有额外奖励的任务还没有被解锁，会被标记为星星。有些特殊待遇也有你可以打开或关闭的效果。",
    "Tasks are the actions you perform. You can start a task and pause it at any time—initially, only one task can run simultaneously. Tasks may use one, two, or three skills, with the speed and energy drain determined by multiplying the speed and drain multipliers from each selected skill. Hovering over a task (or holding on mobile) gives additional info. Note that the energy/time estimates are based on current skill levels - if a skill levels while performing the task then both energy and time will be less.": "任务是您执行的操作。您可以在任何时候启动和暂停任务——最初，只能同时运行一个任务。任务可以使用一个、两个或三个技能，速度和能量消耗取决于每个选择技能的速度和能量消耗乘数。将鼠标悬停在任务上（或在移动设备上）会提供额外的信息。注意，能量/时间估算是基于当前的技能水平——如果在执行任务时技能水平提高了，那么能量和时间都会减少。",
    "This game throws many mechanics at you - feel free to experiment by yourself, but this tutorial will walk you through the basics. As you progress, you'll discover that different stages of the game demand different strategies—what works in the early zones might not be as effective later on.\n      The complexity of resources and their interactions with skills, tasks, and resets scale up very quickly, so if you're looking for a chill, passive idle experience, this may not be the game for you.\n      Instead, be prepared to constantly adapt your strategy to optimize your resource management and efficiency.\n      And hey, if you manage to solve all the strategic puzzles and beat zone 33 with ease, send me your resume!": "这个游戏向你抛出了许多机械-你可以自由地自己尝试，但本教程将引导你完成基础知识。随着游戏的进展，你会发现游戏的不同阶段需要不同的策略——在早期有效的策略在之后可能就不那么有效了。\n      资源的复杂性以及它们与技能、任务和重置的相互作用会迅速扩大，所以如果你正在寻找一种冷静、被动的放置体验，那么这款游戏可能不适合你。\n      相反，要准备好不断调整策略以优化资源管理和效率。\n      嘿，如果你能解决所有的战略难题，轻松击败33区，把你的简历发给我！",
    "Some tasks produce resources. Resources must be consumed to take effect - nearly all effects last until you run out of energy or experience a copium/delusion reset. On an energy reset, you lose half of your resources.": "有些任务产生资源。资源必须消耗才能生效-几乎所有的效果都会持续到你耗尽能量或经历精神/妄想重置。在能量重置时，你会失去一半的资源。",
    "Tutorial & Tips": "教程 & 提示",
    "speed = baseSpeed * (perk 1) * (perk 2)...": "速度 = 基础速度 * (特权 1) * (特权 2)...",
    "speed = baseSpeed * (1 + sum(all resource boosts))": "速度 = 基础速度 * (1 + 总和(所有资源提升))",
    ".\n      Perks persist through energy, copium, and delusion resets. They do however get reset on prestige.": "。\ n福利坚持通过能源、精神，妄想重置。然而，他们的声望确实会被重置。",
    ". \n      The energy drain calculation is: ": "。\n能量消耗计算如下：",
    "Achievements are a one-and-done type of deal - once unlocked you have them forever. They provide a small speed boost to all skills (additive 1% per achievement).": "成就是一种一次性交易——一旦解锁，你就永远拥有它们。它们为所有技能提供了一个小的速度提升（每个成就增加1%）。",
    "Additional sections remain hidden until the corresponding mechanics are unlocked.": "在相应机械被解锁之前，其他部分将一直被隐藏。",
    "Alternate between \"Farm Runs\" (saving resources) and \"Push Runs\" (using both old and new resources for maximum progress).": "在“Farm Runs”（节省资源）和“Push Runs”（同时使用新旧资源以获得最大进度）之间交替进行。",
    "Don't dwell on completing everything in a zone. Often something in later zones will help a lot more.": "不要想着在一个区域内完成所有事情。通常在后面的区域会有更大的帮助。",
    "drain = baseDrain / (1 + sum(all resource boosts))": "消耗= 基础消耗 / （1 + 总计（所有资源提升））",
    "Hover over tasks, skills, resources, perks to view details about them.": "将鼠标悬停在任务、技能、资源和福利上，查看它们的详细信息。",
    "Keep in mind that energy requirements for tasks account for Energetic Bliss (when this perk is unlocked); when your energy drops below 80%, tasks may require more energy.": "请记住，任务的能量需求考虑到精力充沛的幸福（当这个特权被解锁时）；当你的能量低于80%时，任务可能需要更多的能量。",
    "Multi-skill tasks are generally better for grinding XP, especially tasks that use three skills.": "多技能任务通常更适合刷经验，特别是需要使用3种技能的任务。",
    "Once Energy Elixir cost is under 3 per task, it’s usually worth it to produce the max amount on every run.": "一旦每个任务的能量消耗低于3，那么在每次运行中产生最大的能量通常是值得的。",
    "Perk effects stack multiplicatively. If two different perks affect the speed of the same skill, the speed boost is calculated as:": "特权效果叠加成倍数。如果两种不同的技能影响同一技能的速度，速度提升的计算方法为：",
    "Resource boosts stack additively with themselves and with other resources. The skill speed calculation is: ": "资源提升与自身和其他资源叠加。技能速度计算如下：",
    "Source code is open so if you are interested in details of how formulas work, feel free to dive in and explore.": "源代码是开放的，所以如果您对公式如何工作的细节感兴趣，请随意潜入和探索。",
    "When the corresponding perk is unlocked, automation can be customized by toggling tasks on and off. This can be done by right clicking a task (or holding down on mobile).": "当相应的福利被解锁时，可以通过切换任务的开关来定制自动化。这可以通过右键单击任务（或按住手机）来完成。",
    "69 K?": "69 K?",
    "Advance to Zone 2.": "进入第2区。",
    "Advanced Potion Making without having seen any of those potions.": "进阶魔药制作，而不去看那些魔药。",
    "Amnesia": "失忆",
    "Apothecary": "药剂师",
    "Asymptote": "渐近线",
    "Attunement": "协调",
    "Baby Steps": "婴儿学步",
    "Big Game Hunter": "大型猎手",
    "Bookworm": "书呆子",
    "Certified Turtle": "认证海龟",
    "Click all the buttons on main settings page.": "点击主设置页面上的所有按钮。",
    "Complete your first Prestige.": "完成你的第一个威望",
    "Cool Little Brother": "酷小哥",
    "Copium reset with exactly 10 inifinity gauntlets and nothing else.": "精神重置时只有10个无限手套，仅此而已。",
    "Cybernetic Overload": "控制过载",
    "Defeat Agent Smith without using any resources.": "不使用任何资源击败 特工史密斯",
    "Defeat Big Brother after having only used sunglasses.": "在只使用太阳镜的情况下击败老大哥",
    "Defeat Chuck Norris after having used an energy core.": "在使用能量核心后击败查克·诺里斯",
    "Defeat Doctor Manhattan while holding atomic particle (unused).": "手持原子粒子击败曼哈顿博士（未使用）。",
    "Defeat Vegeta with 0 copium.": "使用 0 精神击败贝吉塔",
    "Delusion reset at over 50K delusion.": "妄想重置到超过50K妄想。",
    "Delusional": "妄想症",
    "Empty Pockets": "口袋空空",
    "Energy reset with over 8990 copium.": "能量重置超过8990精神。",
    "First Prestige": "第一声望",
    "Full clear Zone 3.": "完全清除区域3。",
    "Gain at least 69k serenity in one prestige.": "在一个威望中获得至少69k的宁静",
    "Gain over 100 starting energy from cybernetic implants in one run.": "在一次运行中从控制植入物中获得超过100的起始能量。",
    "Googolplex": "古戈尔普勒克斯",
    "Have at least 4 cybernetic armors left after energy reset.": "能量重置后至少有4件控制盔甲",
    "Hold over 200 Energy Elixirs in your inventory at once.": "一次在你的库存中持有超过200个能量酏剂。",
    "I'm Flying": "我在飞翔",
    "Instant Expert": "速成专家",
    "Jedi Master": "绝地大师",
    "Lose over 10K knowledge in a single copium reset.": "在一次精神重置中丢失超过10K的知识。",
    "Lucky": "幸运",
    "Mano a Mano": "短兵相接",
    "Mega Push": "超级推动",
    "Mondo Cool": "绝对的酷",
    "Not Delusional": "不是妄想",
    "Pause a boss fight.": "暂停boss战。",
    "Postpone Inevitable": "推迟不可避免",
    "Prestige 420 times.": "声望420次。",
    "Prestige with zone 7 being your best zone.": "在区域7声望是你最好的区域。",
    "Produce at least 14 resources at once.": "一次生产至少14种资源",
    "Reach your max delusion value exactly.": "正好达到你的最大妄想值。",
    "Reach zone 10 without using any resources and holding over 100 resources.": "在不使用任何资源的情况下到达10区，并且拥有超过100个资源。",
    "Reach zone 11 with zero energy resets.": "在零能量重置的情况下到达11区",
    "Reach Zone 15 without any resources (used or held).": "在没有任何资源（已使用或持有）的情况下到达区域15",
    "Rinnegan": "Rinnegan",
    "Seven": "七个",
    "Slay Godzilla without battling any previous bosses.": "在不与之前的boss战斗的情况下杀死哥斯拉。",
    "Stockpile": "储备",
    "Take a Breather": "休息一下",
    "Take down the Doctor": "干掉博士",
    "That Was Easy": "这很容易",
    "Toggle a perk to disable it.": "切换一个技能来禁用它。",
    "Toggler": "善变者",
    "Try to hold over 9 Googols in your inventory at once.": "尝试一次在你的库存中持有9个以上的 天文数字。",
    "Unlock the Master Ball.": "解锁大师球。",
    "Use cybernetic armor to make an energy elixir.": "使用控制盔甲制造能量药剂",
    "Use radiance when 2 unfinished tasks are above 90% complete.": "当2个未完成的任务完成超过90%时使用radiance。",
    "Use the power of Rinnegan.": "利用里尼根的力量。",
    "Using 1 lightsaber at a time, have it return 5 times in a row.": "一次使用一把光剑，让它连续返回5次。",
    "Wasted Armor": "浪费了盔甲",
    "What XP?": "什么经验？",
    "Stacks multiplicatively.": "堆叠相乘。",
    ", Intellect": "，智力",
    ": Rudimentary Upgrade": "：基本升级",
    ": Run City Marathon": "：跑城市马拉松",
    "Analyze traffic patterns using perception and intellect.": "使用感知和智力分析交通模式。",
    "Assemble Goggles": "组装护目镜",
    "Build yourself some eye protection.": "给自己做一些眼部保护。",
    "Construct a basic biomechanical upgrade.": "构建基本的生物机械升级。",
    "Enter Corporate District": "进入公司区",
    "Fix a Broken Engine": "修理坏了的引擎",
    "Learn the basics of machinery repair.": "学习机械维修的基本知识。",
    ", Intellect": "，智力",
    ", Tinkering": "，铸补",
    "Self-Operating Gadget: Simple Automation": "自动操作装置：简单的自动化",
    "Step into the orderly world of corporate business.": "步入公司业务的有序世界。",
    "Study Urban Traffic Flow": "城市交通流研究",
    "Test your stamina on a long city run.": "在城市长跑中测试你的耐力。",
    "Utilize your mechanical expertise and tinkering skills to build a basic automated system that streamlines routine tasks.": "利用你的机械专业知识和铸补技能来建立一个基本的自动化系统，简化日常任务。",
    ", Mechanics": "，机械",
    ": Finance Bro Advice": "：金融兄弟的建议",
    ": Mechanics of Luck": "：运气机械",
    "Advance to a high-tech cyber environment.": "向高科技网络环境迈进。",
    "Analyze corporate data with intellect and mechanics.": "运用智力和技巧分析公司数据。",
    "Automatically continue tasks until max reps.": "自动继续任务，直到最大的代表。",
    "Battle Agent Smith": "战斗特工史密斯",
    "Build a simple gacha machine.": "制作一台简单的gacha机器。",
    "Business Card Exchange": "交换名片",
    "Click to Toggle this perk.": "点击切换这个福利。",
    "Crunch Financial Numbers": "紧缩的财务数据",
    "Disabled Completionist.": "残疾的完美主义者。",
    "Don't worry, you can move to next zone without it.": "别担心，你可以不带它去下一个区域。",
    "Enabled Completionist.": "启用完成主义者。",
    "Endurance, Charisma, Perception": "耐力，魅力，感知",
    "Engage in simulated corporate conflicts.": "参与模拟的公司冲突。",
    "Learn how workaholics function.": "了解工作狂是如何工作的。",
    "Practice your charisma in a corporate setting.": "在公司环境中练习你的魅力。",
    "Proceed to Cyber Lab": "前往网络实验室",
    "Tactical Office Skirmish Simulation": "战术办公室小规模冲突模拟",
    "Take on this Matrix propagator. Might as well practice Combat.": "取这个矩阵传播子。不妨练习一下格斗。",
    "This button is red - it's a boss fight.": "这个按钮是红色的，这是一场boss战。",
    "OK": "确定",
    ": Study the Basics": "：学习基础知识",
    ": System Revamp": "：系统改造",
    "Battle Shao Kahn": "少卡恩之战",
    "Breach the Firewall": "突破防火墙",
    "Chemical Simulation": "化学模拟",
    "Crack the Cipher": "破解密码",
    "Create a simple amphetamine pill.": "制造一种简单的安非他明药片。",
    "Create an Amphetamine Pill": "制作安非他命药片",
    "Debug Digital Puzzle": "调试数字谜题",
    "Decrypt secret codes.": "解密密码。",
    ", Endurance": "，耐力",
    ", Mechanics": "，机械",
    ", Perception": "，感知",
    ", Tinkering, Intellect": "，铸补，智力",
    "Knowledge Unlocked!": "知识解锁!",
    "Learn basic system penetration.": "学习基本的系统渗透。",
    "Proceed to Combat Arena": "进入战斗竞技场",
    "Revamp a digital system to double its efficiency.": "改造数字系统，使其效率提高一倍。",
    "Simulate a chemical reaction.": "模拟化学反应。",
    "Solve a digital puzzle using coding skills.": "使用编码技巧解决一个数字谜题。",
    "Some clown challenges you to mortal combat.": "一些小丑向你发起致命的挑战。",
    "Step into the arena of combat.": "步入战斗的竞技场。",
    "Study the basics of hacking.": "学习入侵的基础知识。",
    "You now gain +0.1% XP per level for the following skills:": "你现在每等级获得+0.1%的经验为以下技能：",
    "for tinkering, intellect, hacking.": "对于铸补，智力，入侵。",
    "Goggles:": "护目镜:",
    "Knowledge increases XP gain by": "知识增加经验增益",
    "That task is already completed.": "这个任务已经完成了。",
    "Energy is critically low!": "能量极低！",
    "Unlock ability to automate zones after fully completing 10 times.": "完全完成10次后解锁自动化区域的能力。",
    "Full Completes:": "完全完成:",
    "Automate:": "自动化:",
    "Zone": "区域",
    "Run all tasks in current zone.": "运行当前区域中的所有任务。",
    "Run all tasks in automated zones.": "运行自动化区域中的所有任务。",
    "Automation disabled": "自动化已禁用",
    "Automation ended.": "自动化已启用。",
    "Automation set to All mode": "自动化设置为所有模式",
    "Automation set to Zone mode": "自动化设置为区域模式",
    "25% chance to produce double resources.": "25%的几率产生双倍的资源。",
    "Sound Effects are recommended for boss fights. Just for fun!": "建议在Boss战斗中使用音效。只是为了好玩！",
    "Are you sure you want to FULL RESTART? This cannot be undone.": "你确定要重新开始吗？这是无法挽回的。",
    "Cancel": "取消",
    "Knowledge:": "知识:",
    "Knowledge increases your XP gain for related skills. It is earned from tasks that use knowledge-based skills and is crucial for fast leveling and overall progress. Note that knowledge is only gained after completing all repetitions of a task.": "知识可以增加相关技能的经验值。它可以从使用知识技能的任务中获得，对于快速升级和整体进展至关重要。请注意，只有在完成所有重复的任务后才能获得知识。",
    "Load this save? (Page will refresh after loading)": "是否加载此存档？（页面加载后会刷新）",
    "Use All": "使用全部",
    "Use One": "使用1个",
    " is active!": " 已激活！",
    "Allows running two tasks simultaneously.": "允许同时运行两个任务。",
    "But you will permanently gain 6 starting energy.": "但你将永久获得6个起始能量。",
    "Copium builds up from tasks with": "精神从任务中积累起来",
    "endurance, alchemy, mechanics.": "耐力，炼金术，机械。",
    "for combat, endurance.": "对于战斗，耐力。",
    "If it exceeds 9000, your game will reset": "如果超过9000，你的游戏将重置",
    "Increase starting Energy gained for each Copium reset to +6.": "每重置一次精神所获得的起始能量为+6。",
    "Power increases speed by": "力量增加速度",
    "Reduce Hacking energy drain by 10%.": "减少10%的入侵能量消耗。",
    "While energy is above 80%, task progress is doubled.": "当能量超过80%时，任务进度翻倍。",
    "with all Resources and half your Knowledge lost!": "失去了所有的资源和一半的知识！",
    "Amphetamine Pill:": "安非他命药丸:",
    "And Makes you look cool.": "让你看起来很酷。",
    "Cool Sunglasses:": "酷的太阳镜:",
    "Reduces Endurance and Combat energy drain by 10%.": "减少10%的耐力和战斗能量消耗。",
    "Reduces Hacking energy drain by 100%.": "减少100%的入侵能量消耗。",
    "Reduces Tinkering and Hacking energy drain by 5%.": "减少铸补和入侵 5% 的能量消耗。",
    "Steroids:": "类固醇:",
    ", Intellect": "智力",
    ", Quantum": "，量子",
    ", Charisma": "，魅力",
    ", Endurance, Perception": "，耐力，感知",
    ", Hacking": "，入侵",
    ": Find a Tool": "：找一个工具",
    ": Painstaking Training": "：艰苦的训练",
    ": Synthesize a Contraption": "：合成一个精巧装置",
    ": Talk Your Way": "：用你的方式说话",
    "Battle Sauron": "索伦之战",
    "Calibrate cybernetic systems.": "校准控制系统。",
    "Challenge Dojo Master Chuck Norris": "挑战道场大师查克·诺里斯",
    "Challenge the legendary martial artist.": "挑战传奇武术家。",
    "Climb to the city rooftop.": "爬上城市的屋顶。",
    "Concoct Some Steroids": "调制一些类固醇",
    "Convince the masters to help you improve your learning.": "说服大师帮助你提高你的学习。",
    "Create a contraption using advanced techniques.": "使用先进的技术创建一个精巧的装置。",
    "Create a performance-enhancing steroid.": "制造一种提高成绩的类固醇。",
    "Descend deeper into the digital realm.": "深入到数字领域。",
    "Develop team-based combat strategies.": "开发基于团队的战斗策略。",
    "Endurance, Alchemy, Mechanics": "耐力，炼金术，机械",
    "Engage in a grueling training session.": "参加艰苦的训练课程。",
    "Exosuit Upgrade Overhaul": "外衣升级大修",
    "Learn the fundamentals of combat.": "学习战斗的基本原理。",
    "Locate a futuristic wrench.": "找到一个未来的扳手。",
    "Navigate to Abandoned Factory": "前往废弃工厂",
    "Neural Implant Test": "神经植入试验",
    "Practice with simulated weapons.": "使用模拟武器进行练习。",
    "Proceed to Rooftop Rendezvous": "前往天台会合",
    "Save Some Touchable Grass": "保存一些可触摸的草",
    "Simulated Weapon Drills": "模拟武器演习",
    "Sparring Session": "切磋环节",
    "Spot touchable grass and pick some for later.": "找到可触摸的草，摘一些供以后使用。",
    "System Calibration Diagnostic Run": "系统校准诊断运行",
    "Tactical Group Skirmish": "战术群战",
    "Take on the creator of just one ring.": "和一戒的创造者较量一下。",
    "Test cutting-edge neural implants.": "测试尖端的神经植入物。",
    "Upgrade your cybernetic exosuit.": "升级你的控制服。",
    "It's over 9000! Your copium that is.": "超过9000了！那是你的精神。",
    "You lose all your resources and half your knowledge.": "你失去了所有的资源和一半的知识。",
    "Copium builds up from tasks that use copium-related skills, and reaching max copium will reset the game. Keep in mind that copium can be used to your advantage. Later in the game, strategies utilizing copium become essential.": "精神是通过使用精神相关技能的任务而建立起来的，达到最大精神将重置游戏。记住，精神可以为你所用。在游戏后期，利用精神的策略变得至关重要。",
    "Power:": "力量:",
    "Copium:": "精神:",
    "Power boosts the speed of power-related tasks (initially Combat and Endurance) and is obtained by defeating bosses.": "力量可以提高力量相关任务的速度（最初是战斗和耐力），并通过击败Boss获得。",
    " drains 3x less energy.": "消耗能量减少3倍。",
    " to the forsaken bastion.": "去被遗忘的堡垒。",
    ", Quantum": "，量子",
    ": Energy Galore": "：能源丰富",
    ": Haggle for it": "：讨价还价",
    "25x increased charisma XP gain.": "增加25倍魅力经验值。",
    "5x increased AI Mastery XP gain.": "AI精通经验增加5倍。",
    "7% chance to produce 7x resources.": "7%的机会生产7x资源。",
    "A high-tech take on social engineering.": "一个高科技的社会工程。",
    "Algorithm Optimization": "算法优化",
    "All XP gains increased by 28%.": "所有经验值增加28%。",
    "And decrease Charisma energy drain by 28%.": "减少28%的魅力能量消耗。",
    "And makes you look more shiny.": "让你看起来更有光泽。",
    "Any task ending or pausing task will remove the armor.": "任何任务结束或暂停都会移除盔甲。",
    "Attempt to create a sentient crystal.": "尝试创造一个有知觉的水晶。",
    "Create a quantum vitalizer for health benefits.": "为健康创造一种量子活力剂。",
    "Cybernetic Armor:": "控制盔甲：",
    "Deplot Cyber Barrier": "部署网络屏障",
    "Deploy a robust digital defense.": "部署强大的数字防御。",
    "Experiment with quantum particles.": "用量子粒子做实验。",
    "Find a map to the forsaken bastion.": "找到一张去被遗忘堡垒的地图。",
    "Find Map to Forsaken Bastion": "找到去被遗忘堡垒的地图",
    "Haggle with a science nerd.": "和一个科学迷讨价还价。",
    "Hyperlink Manipulation": "超链接操作",
    "Improves automation to allow selecting individual tasks.": "改进自动化，允许选择单独的任务。",
    "Increase travel speed by 4x.": "使行进速度提高4倍。",
    "Multiple uses stack with # of tasks, not with drain.": "多重使用堆栈与#的任务，而不是与drain。",
    "Proceed to Forsaken Bastion": "前往被遗忘堡垒",
    "Random Crystal: Sentience Attempt": "随机水晶：感知尝试",
    "Reduce Copium gain by 60%.": "减少60%精神的增益。",
    "Reduce minimum energy drain by 75%.": "减少75%的最小能量消耗。",
    "Reduces Combat energy drain by 100%.": "减少战斗能量消耗100%。",
    "Reduces energy drain by 75% for next task (one square).": "为下一个任务减少75%的能量消耗（一个方格）。",
    "Refine and optimize complex algorithms.": "完善和优化复杂的算法。",
    "Right click a task to toggle automation.": "右键单击任务以切换自动化。",
    "Shiny Helmet:": "闪亮头盔：",
    "Subatomic Experiment": "亚原子实验",
    "This affects tasks that are completed in one tick.": "这会影响在一个tick内完成的任务。",
    " Vitalizer: Energy Galore": "活力：能量充沛",
    ", AiMastery": "， Ai精通",
    ", Combat": "，战斗",
    ", Cybernetics": "，控制",
    ": Adopt a Dog": "：领养一只狗",
    ": Decent Algorithm": "：体面的算法",
    ": Find the Clover": "：找到三叶草",
    ": Steal One": "：偷一个",
    ": Ultimate Feat of Engineering": "工程的终极壮举",
    "Adopt a loyal dog.": "领养一只忠诚的狗。",
    "Battle Isshin": "伊信之战",
    "Battle Kratos": "奎托斯之战",
    "Broker a Tactical Deal": "撮合一笔策略性交易",
    "Carefully craft a cybernetic armor.": "精心制作一件控制盔甲。",
    "Challenge the demi-god.": "挑战半神。",
    "Challenge the master of the blade.": "向剑术大师挑战。",
    "Climb out to the bustling Techno District.": "爬到熙熙攘攘的科技区。",
    "Copius Alchemist: Advanced Manual": "科皮乌斯炼金术士：高级手册",
    "Create a cybernetic potion.": "创造一种控制药水。",
    "Create the ultimate feat of engineering.": "创造工程学的终极壮举。",
    "Cybernetic Armor": "控制盔甲",
    "Cybernetic Potion": "控制药水",
    "Cybernetic Potion:": "控制药水：",
    "Descend to Digital Underground": "进入数码地下",
    "Digital Data Frenzy Challenge": "数字数据狂潮挑战",
    "Emerge into Techno District": "进入科技区",
    "Engage in simulated digital battles.": "参与模拟的数字战斗。",
    "Enhance and optimize neural networks.": "增强和优化神经网络。",
    "Extract and decode hidden data.": "提取和解码隐藏的数据。",
    "Extract Encrypted Secrets": "提取加密的秘密",
    "Head back into the digital depths.": "回到数字世界的深处。",
    "Head to the hub of advanced AI research.": "前往高级人工智能研究中心。",
    "Hone your negotiation skills in high places.": "在高处磨练你的谈判技巧。",
    "Leverage AI to create a cybernetic combat enhancement.": "利用AI创造一个控制的战斗增强。",
    "Locate a lucky clover.": "找到幸运的三叶草。",
    "Omega Resonator: Cybernetic Enhancement": "欧米茄共振器：控制增强",
    "Optimize the Neural Net System": "优化神经网络系统",
    "Override the Grid": "覆盖网格",
    "Persuade the High-Rise Crowd": "说服高层人士",
    "Process rapid streams of digital data.": "处理快速的数字数据流。",
    "Reduced Combat energy drain by 100%.": "减少战斗能量消耗100%。",
    "Reduced energy drain by 75% for next 2 tasks": "在接下来的2个任务中减少75%的能量消耗",
    "Reduces Cybernetics energy drain by 20%.": "减少控制能量消耗20%。",
    "Run selected tasks in automated zones.": "在自动化区域中运行选定的任务。",
    "Run selected tasks in current zone.": "运行当前分区中选定的任务。",
    "Steal a hoverboard for high-speed travel.": "偷一个悬浮滑板来进行高速旅行。",
    "Study advanced alchemical techniques.": "学习先进的炼金术。",
    "Take control of the city's digital infrastructure.": "控制城市的数字基础设施。",
    "Tinkering, Cybernetics": "铸补，控制",
    "Tinkering, Cybernetics, Hacking": "铸补，控制，入侵",
    "Train a reinforcement learning algorithm.": "训练一个强化学习算法。",
    "Use your wit to sway opinions.": "用你的智慧来左右别人的意见。",
    "Venture to Research Facility": "投资研究设施",
    "Virtual Simulated Skirmish": "虚拟模拟战斗",
    " Training": "训练",
    " Vitalizer:": "活力剂：",
    ", Negotiation": "，谈判",
    ": Guerrilla Warfare Sprint": "：游击战冲刺",
    ": Knowledge Expansion": "：知识拓展",
    ": New Invention": "：新发明",
    ": System Repair": "：系统维修",
    "Approach a dazzling metropolis of the future.": "接近一个耀眼的未来大都市。",
    "Battle Deadpool": "死侍之战",
    "Battle Vegeta": "贝吉塔之战",
    "Beg for Ascension": "祈求转生",
    "Boosted Combat speed by 240%.": "战斗速度提高240%",
    "Boosts Combat speed by 20%.": "提高20%的战斗速度。",
    "Breach a secure digital vault.": "破坏一个安全的数字保险库。",
    "Breach an enemy outpost undetected.": "潜入敌人的前哨而不被发现。",
    "Challenge the merc with a mouth.": "用嘴挑战雇佣兵。",
    "Challenge the prince of all Saiyans.": "挑战所有赛亚人的王子。",
    "charisma, perception, aiMastery, negotiation.": "魅力，感知，AI精通，谈判。",
    "Convince ascended beings to let you access their metropolis.": "说服扬升生物让你进入他们的大都市。",
    "Create a machine that preserves knowledge.": "创造一台保存知识的机器。",
    "Create a potion that cleanses the mind.": "创造一种净化心灵的药剂。",
    "Delusion builds up from tasks with": "妄想是由任务产生的",
    "Endurance, Combat": "耐力，战斗",
    "Ex: energy reset on zone 8 gives +0.8 starting energy.": "例如：能量重置在区域8给予+0.8开始能量。",
    "Exit to Shattered Expanse": "出口到破碎苍穹",
    "Expand your knowledge of mechanics.": "扩展你的力学知识。",
    "Gain Zone / 10 starting Energy for each Energy reset.": "每重置一次能量，获得10个起始能量。",
    "High-Intensity Bunker Blitz Drill": "高强度地堡闪电战演习",
    "Infuse a Sanity Cleanser": "注入健康清洁剂",
    "Journey back to the shattered expanse.": "回到破碎苍穹。",
    "Journey to Exalting Metropolis": "提升大都会之旅",
    "Knowledge also levels with and boosts Mechanics.": "知识也能够提升机制。",
    "Levels up a random skill to next level.": "将随机技能升级到下一个级别。",
    "Omega Resonator:": "欧米伽共鸣器：",
    "Produce Augment Fuel": "生产补充燃料",
    "Push your endurance to the limit in a confined space.": "在有限的空间里把你的耐力推到极限。",
    "Random Crystal:": "随机水晶:",
    "Reduce all skill XP scaling from 2% to 1.9%.": "减少所有技能经验从2%到1.9%。",
    "Reduce Knowledge loss on copium reset by 80%.": "减少量子重置时80%的知识损失。",
    "Reduce Quantum energy drain by 40%.": "减少量子能量消耗40%。",
    "Repair and optimize atomic systems.": "修复和优化原子系统。",
    "Secure Vault Access Code Breaker": "安全保险库访问破码器",
    "Silent Outpost Infiltration": "无声前哨渗透",
    "Sprint through a raging sandstorm.": "在肆虐的沙尘暴中冲刺。",
    "Synethesize some augment fuel.": "合成一些补充燃料。",
    "Tinkering, Intellect": "铸补，智力",
    "Tinkering, Intellect, Mechanics": "铸补，智力，力学",
    "Train for long-distance travel.": "长途旅行的训练。",
    "with 20% of your Power lost!": "失去了20%的能量！",
    "with all Resources and 10% of your Knowledge lost!": "失去所有的资源和10%的知识！",
    "You lose all your resources and 10% of your knowledge.": "你失去了所有的资源和10%的知识。",
    "Delusion, like copium, builds up through tasks using delusion-related skills and reaching max will reset the game. Throughout the game, more delusion-related features will unlock, and keeping it balanced will be very beneficial. Though initially it may seem only negative, a delusion reset causes no resource loss, which can help build powerful runs.": "妄想，就像精神，通过使用妄想相关技能的任务来建立，达到最大值将重置游戏。在整个游戏过程中，更多与妄想相关的功能将被解锁，保持平衡将是非常有益的。虽然一开始它可能看起来只是消极的，但妄想重置不会造成资源损失，这有助于构建强大的运行。",
    "And reduces Negotiation energy drain by 100%.": "并减少谈判能量消耗100%。",
    "Boosts Charisma speed by 25%.": "使魅力速度提高25%。",
    "By letting them know you are a ninja.": "让他们知道你是忍者。",
    "Delusion:": "妄想：",
    "for tinkering, intellect, hacking, mechanics.": "为了铸补，智力，黑客，机制。",
    "Karate Belt:": "空手道腰带:",
    " Harmony: Unlock perk on Zone 18.": "和谐：解锁区域18的特权。",
    " Teleportation: Unlock perk on Zone 17.": "传送：解锁区域17的特权。",
    " Vitalizer: Unlock perk on Zone 11.": "激活：解锁区域11的特权。",
    "Exit": "退出",
    " gives +100 energy instead of +25.": "提供+100点能量，而不是+25点。",
    " produces triple resources instead of double.": "产生三倍资源而不是两倍。",
    " reduces Copium drain by 80% instead of 60%.": "减少80%的Copium流失，而不是60%。",
    ": Nebula Soil": "：星云土",
    ": Radiodynamic Gardening": "：放射动力园艺",
    ": Test of Endurance": "：耐力测试",
    "• Data Bit: 1% chance to find 1-10 (random) Data Bits": "•数据位：1%的机会找到1-10（随机）数据位",
    "• Energy: 25% chance to gain 50 Energy (": "•能量：25%的几率获得50点能量(",
    "• Knowledge: 10% chance to gain 50 Knowledge (": "•知识：10%的几率获得50点知识(",
    "• Power: 5% chance to gain 50 Power (": "•力量：5%的几率获得50点力量(",
    "• Serenity: 2.5% chance to stash 2.5% of base potential Serenity": "•宁静：2.5%的几率隐藏2.5%的基础潜力宁静",
    "Add auto consume option that leaves 1 of every resource": "添加自动消耗选项，每个资源留下1",
    "Adds toggle for auto consuming resources.": "增加自动消耗资源的开关。",
    "and on Prestige, start with growth miracle perk unlocked.": "在威望，开始与增长奇迹perk解锁。",
    "Attain Equilibrium (not available yet)": "达到平衡（暂不可用）",
    "Automation order can now be fine tuned for each zone.": "自动化顺序现在可以对每个区域进行微调。",
    "Battle Thanos (with hair)": "灭霸之战（有头发）",
    "Become the Void (not available yet)": "变成虚空（暂时不可用）",
    "Best Full Zone": "最佳全区",
    "Better Elixirs": "更好的灵丹妙药",
    "Click to access the Prestige menu.": "点击进入声望菜单。",
    "Click to Load, Right Click to Save (Hold on Mobile)": "点击加载，右键保存（在手机上保持）",
    "Cognitive Cache": "认知缓存",
    "Complete Workaholic": "完整的工作狂",
    "Copiouser Alchemist": "丰富的炼金术士",
    "Crystal Collector": "水晶收集器",
    "Cultivate the garden with care and vigor.": "细心而有活力地栽培花园。",
    "Cyber Onslaught": "网络攻击",
    "Delusion Enjoyer": "妄想享乐者",
    "Delusion Immune": "妄想免疫",
    "Digital Mainframe Break-In": "数字主机入侵",
    "Discover Serenity": "发现宁静",
    "Divide all energy drain by (# perks unlocked / 10).": "将所有能量消耗除以（#已解锁的特权/ 10）。",
    "Each time you travel:": "每次旅行时：",
    "Embrace Stillness": "享受安静",
    "Enable automation for tasks in order you want them to run.": "为要运行的任务启用自动化。",
    "Engage the Mad Titan in a clash of cosmic might. Maybe even take his glove.": "在宇宙力量的冲突中与疯狂泰坦交战。甚至可以拿走他的手套。",
    "Enter The Garden": "走进花园",
    "Entropy Shield": "熵盾",
    "Experience Junkie": "体验狂",
    "Fortune's Favor": "财富杂志的支持",
    "fully cleared zones and automation settings preserved.": "完全清除区域和自动化设置保留。",
    "Gacha Overdrive": "扭蛋超速",
    "Game Speed": "游戏速度",
    "Gather rare blossoms that glow with otherworldly light.": "收集稀有的花朵，闪耀着超凡脱俗的光芒。",
    "Greater Reactor": "更大的反应堆",
    "Harness the power of mechanical gardening.": "利用机械园艺的力量。",
    "Harvest Celestial Blossoms": "收获天体开花",
    "Improve four leaf clover perk by +1% chance and +1 resource.": "提高四叶草技能+1%几率和+1资源。",
    "Improve Noob Haxor energy drain reduction by 1% (asymptotically).": "将新手Haxor的能量消耗降低1%（渐近）。",
    "Improves Crypto Wallet:": "改进加密钱包：",
    "Increase all XP gains by 50% (additively).": "增加50%的经验值。",
    "Increase copium reactor starting energy gain by +1.": "增加精神反应堆启动能量增益+1。",
    "Increase effect of Energy Elixir by +1.": "增加能量药剂的效果+1。",
    "Increase exponent of zone in serenity gain function by +0.1.": "增加宁静增益函数的区域指数+0.1。",
    "Increase max Delusion by 1000.": "妄想最大值提高1000。",
    "Increase starting level of ALL skills after Prestige by +1.": "声望之后所有技能的起始等级提高1。",
    "Infinites": "无限",
    "Instant Simulation": "即时模拟",
    "Journey to Nebular Nexus": "星云联结之旅",
    "Kung Fu Master": "功夫大师",
    "Launch a final digital assault on enemy systems.": "对敌方系统发动最后的数字攻击。",
    "Leave The Garden behind and step into cosmic wonder.": "离开花园，步入宇宙奇观。",
    "Master of AI: Ultimate Challenge": "AI精通：终极挑战",
    "Multiplies serenity gain by +1% * (highest fully completed zone).": "使宁静增加+1% *（最高完全完成区域）。",
    "Multiply Knowledge gain by percentage equal to current level of Delusion (min 100%).": "将获得的知识乘以等于当前妄想等级的百分比（最低100%）。",
    "Multiply power gained from defeating bosses by 2x (multiplicatively).": "将击败boss获得的能量乘以2倍（相乘）。",
    "Must be purchased before getting perk.": "必须在获得福利之前购买。",
    "Nurture Cosmic Flora": "培育宇宙植物群",
    "On Copium reset, keep one random random resource per level.": "在精神重置中，每关保留一个随机资源。",
    "On Prestige, start with completionist and workaholic perks unlocked.": "在声望中，首先解锁完美主义者和工作狂的特权。",
    "On Prestige, start with kung fu zen perk unlocked.": "在威望，开始与功夫禅宗振作解锁。",
    "On Prestige, start with Self Operating Gadget and Simulation Engine unlocked,": "在威望，开始与自我操作的小工具和模拟引擎解锁，",
    "Only consumes resources that affect whole run.": "只消耗影响整个运行的资源。",
    "Penetrate a heavily fortified digital fortress.": "突破一个戒备森严的数字堡垒。",
    "Plant Seeds of Creation": "植物创造的种子",
    "Power Doubler": "力量倍增器",
    "Prestige": "声望",
    "Prune Stellar Vines": "修剪星藤",
    "Random Crystal gives +1 more level.": "随机水晶使等级提升1。",
    "Reduce game tick duration by 1% (asymptotically).": "减少游戏时间1%（渐进）。",
    "Reduce minimum energy drain by 2% (asymptotically).": "减少最小能量消耗2%（渐近）。",
    "Remove AI Mastery from Delusion accumulation.": "从妄想积累中移除AI精通。",
    "Repurpose Perks": "重新津贴",
    "Resource Consumer": "资源消费",
    "Resource Guru": "资源专家",
    "Resource Saver": "节省资源",
    "Satoshi's Wallet": "中本聪钱包",
    "Serenity Gain = (": "宁静增益= (",
    "Serenity Infusion": "宁静灌注",
    "Smarter Automation": "智能自动化",
    "Solve a complex algorithm that tests your intellect.": "解决一个复杂的算法来测试你的智力。",
    "Sow the first seeds in fertile soil.": "把第一批种子播种在肥沃的土壤里。",
    "Starting Level": "起始等级",
    "Stronger Mech": "更强的动力机械",
    "Study the soil here to learn how to accelerate growth.": "研究这里的土壤，学习如何加速生长。",
    "This affects tasks that are completed instantly.": "这会影响立即完成的任务。",
    "This section is locked.": "该区域被锁定。",
    "Tinkering, Perception": "铸补，感知",
    "Total Resets": "总重置",
    "Transcend Chaos": "超越混乱",
    "Trim and shape the living tendrils of cosmic life.": "修剪和塑造宇宙生命的生命卷须。",
    "Triple effect of Workaholic and Celestial Light perks.": "工作狂和天光的三重效果。",
    "Triples effect of Power.": "力量的三倍效果。",
    "Unlock 4 automation profile slots.": "解锁4个自动化配置文件槽",
    "Unlockables": "可解锁物品",
    "Where could the journey take you next?": "接下来的旅程会带你去哪里？",
    "Wisdom Seeker": "智慧的探索者",
    "Withstand an endless onslaught of foes.": "抵挡敌人无休止的攻击。",
    "Zone Pusher": "区域推进器",
    "Confirm": "确认",
    "Confirm Prestige": "确认声望",
    "Automation disabled.": "自动化 已禁用。",
    "Serenity is tied to the prestige mechanic. Your prestige bonus depends on how efficiently you reset—fewer resets yield a higher bonus. Prestige can be performed as many times as you want, and serenity gains stack—so don't worry too much about being inefficient on your first few prestiges.": "宁静与声望机制紧密相连。你的声望奖励取决于你重置的效率——重置次数越少，奖励就越高。声望可以按照你的意愿执行多次，宁静可以获得堆叠，所以不要太担心你的前几次声望效率低下。",
    "And wards off potential mates.": "",
    "At random, either gain 100 Energy,": "随机获得100能量，",
    "At random, reduce Copium or Delusion by 75.": "随机减少精神或妄想75。",
    "Augment Fuel:": "补充燃料：",
    "Beating Heart:": "跳动的心脏:",
    "Blades Of Chaos:": "混乱之刃：",
    "But also reduces energy drain of Perception by 300%.": "同时减少感知能量消耗300%。",
    "charisma, perception, negotiation.": "魅力，感知，谈判。",
    "Katana:": "武士刀：",
    "Oddly enough, only boosts Combat speed by 10%.": "奇怪的是，只能提高10%的战斗速度。",
    "One Ring:": "一戒：",
    "or reduce Copium by 1000": "或将精神减少1000",
    "or reduce Delusion by 1000.": "或减少妄想1000点。",
    "225 and Delusion by 300.": "225和妄想300。",
    "Reduced energy drain by 75% for next task": "为下一个任务减少75%的能量消耗",
    "Reduces Combat and Quantum energy drain by 25%.": "减少25%的战斗和量子能量消耗。",
    "Reduces Copium by 100.": "使精神减少100。",
    "Reduces Delusion by a random number between 1 and 200.": "减少妄想的数值为1到200之间的随机数。",
    "Sanity Cleanser:": "健康清洁剂：",
    "There are multiple prestige sections available - each one unlocks by completing its corresponding task. Once unlocked, that section will remain available for future prestiges.": "游戏中存在多个威望区域，每个区域都需要完成相应的任务才能解锁。一旦解锁，该部分将保留用于未来的声望。",
    "Touchable Grass:": "可触摸的草：",
    "While looking like a badass.": "同时看起来像个坏蛋。",
    ": Digital Onslaught": "：数字冲击",
    ": Find on Street": "：在街上找到",
    "Ascend to Nexus of Infinity": "转生到无限联结",
    "Boosted Combat speed and reduced energy drain by 75%.": "提高战斗速度，减少75%的能量消耗。",
    "Challenge Big Brother": "挑战老大哥",
    "Challenge Big Brother.": "挑战老大哥。",
    "City Grid Neural Sync Optimization": "城市网格神经同步优化",
    "Conquer the Nexus of Infinity.": "征服无限联结。",
    "Corporate Information Espionage": "企业信息间谍活动",
    "Engage in a fast-paced digital battle.": "参与快节奏的数字战争。",
    "Find a lost crypto wallet.": "找到丢失的加密钱包。",
    "Optimize urban networks with quantum precision.": "以量子精度优化城市网络。",
    "Prepare Hoverboard Fuel": "准备悬浮板燃料",
    "Reduces Combat energy drain and boosts Combat speed by 75%.": "减少战斗能量消耗，提高战斗速度75%。",
    "Saiyan Armor:": "赛亚人盔甲：",
    "Steal confidential data using your omniscient insight.": "利用你无所不知的洞察力窃取机密数据。",
    "Synthesize some fuel for your hoverboard.": "为你的悬浮滑板合成一些燃料。",
    "Tinkering, Alchemy": "铸补，炼金术",
    " Fuel:": " 燃料:",
    ": Digital Resonance": "：数字共鸣",
    "Amplify the power of cybernetic energy.": "放大控制能量的力量。",
    "Ascend to Cosmic Forge": "转生至宇宙熔炉",
    "Battle Unicron": "宇宙大帝之战",
    "Charm the Data Streams": "为数据流添加魅力",
    "Confront the colossal force of cosmic destruction.": "面对宇宙毁灭的巨大力量。",
    "Extract Nano Components": "提取纳米成分",
    "Increase # of resource generating tasks by 50%.": "增加50%的资源生成任务。",
    "Interface with Machine Spirits": "与机器精灵接口",
    "Leave the realm of circuits for the fires of creation.": "离开电路的王国，投入创造之火。",
    "Merge your mind with digital deities.": "将你的思想与数字神灵融合。",
    "Optimize Circuitry Harmony": "优化电路和谐",
    "Refine the balance of celestial circuits with precision.": "精练天体电路的平衡。",
    "Scavenge vital microchips from abandoned systems.": "从废弃的系统中清除重要的微芯片。",
    "Use your intellect and charisma to infuse digital data with a harmonious energy.": "用你的智慧和魅力为数字数据注入和谐的能量。",
    "Nano Component:": "纳米成分:",
    "But you will permanently gain 100 starting energy.": "但你将永久获得100初始能量。",
    "Puzzle Piece: Destiny": "拼图：命运",
    "Find inner peace and serenity.": "寻找内心的平静和宁静。",
    " Harmony: Uncertainty Principle": "和谐：不确定性原理",
    " Teleportation: Early Research": "传送：早期研究",
    ", Alchemy": "，炼金术",
    ": +25 Knowledge": "： +25知识",
    ": Nebular Inspiration": "星云灵感",
    "Adjust the flow of cosmic energies to create balance.": "调整宇宙能量的流动以创造平衡。",
    "Adjust the frequencies of unseen oscillations.": "调整看不见的振荡频率。",
    "Align Nebula Currents": "排列星云流",
    "Battle Darth Vader": "达斯·维德之战",
    "Battle Ultron": "奥创之战",
    "Bend the fabric of space-time as you leave the abyss.": "在你离开深渊的时候扭曲时空结构。",
    "Blend chaos and order into perfect symmetry.": "将混乱和秩序融合成完美的对称。",
    "Calibrate Luminous Instruments": "校准发光仪器",
    "Calibrate Waveform Oscillations": "校准波形振荡",
    "Chart the intricate network of nebular pathways.": "绘制星云路径的复杂网络。",
    "Collect Quantum Residue": "收集量子残基",
    "Collect Stardust Samples": "收集星尘样本",
    "Confront the synthetic menace in a clash of logic.": "在逻辑的冲突中面对合成的威胁。",
    "Depart the Nebular Nexus and approach the realm of probabilities.": "离开星云连接点，进入概率领域。",
    "Dive into the realm of probabilistic wonders.": "潜入概率奇迹的领域。",
    "Embrace Quantum Uncertainty": "拥抱量子不确定性",
    "Engage the dark enforcer in an intergalactic duel.": "在星际决斗中与黑暗执行者交战。",
    "Fine-tune devices to capture the brilliance of nebular light.": "微调装置来捕捉星云光的亮度。",
    "Gather sparkling particles scattered across the void.": "收集散落在虚空中的闪闪发光的颗粒。",
    "Harness subatomic forces with precise adjustments.": "精确调节亚原子力。",
    "Intergallactic Farming": "星际农场",
    "Journey to Quantum Abyss": "量子深渊之旅",
    "Learn to grow crops that thrive in the vast expanse of the nebula.": "学会种植庄稼，让它们在浩瀚的星云中茁壮成长。",
    "Let the glow of the cosmos spark creative genius.": "让宇宙的光芒激发创造性的天才。",
    "Map Celestial Grid": "绘制天格图",
    "Navigate the nebula with the power of quantum teleportation.": "用量子隐形传态的力量导航星云。",
    "Retrieve fleeting particles left in the void.": "找回留在虚空中的稍纵即逝的粒子。",
    "Stabilize Particle Field": "稳定粒子场",
    "Tinkering, Quantum": "铸补，量子",
    "Warp to Cybernetic Olympus": "跃迁到控制的奥林匹斯",
    " Harmony:": "和谐:",
    " is now affected by Power.": "现在受到力量的影响。",
    " Teleportation:": "传送:",
    ": Mold Strength": "：模具强度",
    ": Resonate with Flames": "：与火焰共鸣",
    "another random skill also levels up.": "另一个随机技能也会升级。",
    "Auto-Use": "自动使用",
    "Auto-use all resources except:": "自动使用所有资源，除了：",
    "Battle Doctor Manhattan": "曼哈顿战地医生",
    "Combine elements to form structures of eternal strength.": "将各种元素结合起来，形成具有永恒力量的结构。",
    "Comprehend the stillness of the cosmos.": "领悟宇宙的宁静。",
    "Contend with the enigmatic force of atomic power.": "与原子力量的神秘力量抗衡。",
    "Each time Cybernetics levels up,": "每次控制论升级，",
    "Emerge into Celestial Dominion": "进入天界",
    "Exit the blazing forge and ascend toward divine realms.": "离开炽热的熔炉，升入神圣的领域。",
    "Extract Celestial Ore": "提取天体矿石",
    "Gain +1 of every resource you currently have.": "获得+1你目前拥有的所有资源。",
    "Hammer the Celestial Anvil": "锤击天体铁砧",
    "Heat the Stellar Crucible": "加热恒星坩埚",
    "Ignite the furnace of creation to mold the universe.": "点燃创造的熔炉来塑造宇宙。",
    "Infinity Gauntlet": "无限手套",
    "Infinity Gauntlet:": "无限手套:",
    "Let the heat of creation empower your spirit.": "让创造之热赋予你精神力量。",
    "Mine rare metals from the heart of a star.": "从恒星的中心开采稀有金属。",
    "Remove Copium gain related to Mechanics.": "移除与机械相关的铜增益。",
    "Serenity Gain on Prestige increased by 50%.": "宁静的声望增益增加50%。",
    "Shape raw cosmic materials with divine precision.": "以神圣的精确度塑造原始的宇宙物质。",
    "Sparring with Dwarf King": "与矮人王切磋",
    "Stardust": "星尘号",
    "Test your strength against the might of the dwarf king.": "测试你的力量对抗矮人国王的力量。",
    "Tinkering, Endurance": "铸补，耐力",
    "Very few resources cannot be created by Infinity Gauntlet.": "极少数资源无法通过无限护手创造。",
    " energy drain changed by": "能量消耗改变为",
    " Residue:": "残留：",
    " speed changed by": "速度变化为",
    "(cannot affect Omniscience, Totality, or Nihility)": "（不能影响全知、整体或虚无）",
    "1 extra lightsaber spawned!": "1个额外的光剑！",
    "50% chance to spawn an extra Lightsaber.": "50%的几率生成额外的光剑。",
    "5x experience gain next task": "下一个任务获得5倍经验值",
    "a random skill by anywhere from -10% to +50%.": "一个随机技能减少-10%到+50%。",
    "And brings about a surveillance state.": "并带来了一个监视国家。",
    "and reduced energy drain by 46%.": "并减少了46%的能源消耗。",
    "Any task ending or pausing task will remove the shard.": "任何任务结束或暂停都将删除该shard。",
    "Boosts speed for all skills by 3% per use.": "每次使用使所有技能的速度提高3%。",
    "Boosts Tinkering progress and reduces its energy drain": "提高铸补进度，减少能量消耗",
    "by a random percentage (1%-50%) per use.": "每次使用随机百分比（1%-50%）。",
    "Cannot create Infinity Gauntlet.": "无法创建无限挑战。",
    "Create 1 of a random resource that you used this run.": "创建本次运行中使用的随机资源的1个。",
    "Find a piece of the ultimate puzzle to shape your destiny.": "找到一块最终的拼图来塑造你的命运。",
    "for Perception, Intellect, Hacking, and Cybernetics.": "为感知，智力，黑客和控制论。",
    "Increases experience gain by 5x for next task (one square).": "下一个任务的经验值提高5倍（一个方格）。",
    "Lightsaber:": "光剑:",
    "Multiple uses stack with # of tasks, not with xp gain.": "多重使用堆栈#的任务，而不是经验增益。",
    "Puzzle Piece:": "拼图:",
    "100% for Perception, Intellect, Hacking, and Cybernetics.": "感知，智力，黑客和控制论100%。",
    "50% for Perception, Intellect, Hacking, and Cybernetics.": "50%为感知、智力、黑客和控制论。",
    "1000% for Endurance.": "1000%耐力。",
    "Stardust:": "“星尘”号:",
    "Unexpectedly affect speed or energy drain of": "意外影响速度或能量的消耗",
    "for combat, endurance, travel.": "对于战斗，耐力，旅行。",
    "endurance, alchemy.": "耐力，炼金术。",
    "with all but 16 Resources and 10% of your Knowledge lost!": "除了16种资源和10%的知识之外，你已经失去了所有的资源！",
    "Resource Auto-Use disabled": "资源 自动使用 已禁用",
    "Resource Auto-Use enabled": "资源 自动使用 已启用",
    "Multiply Combat speed by cube root of unspent Serenity.": "战斗速度乘以未消耗的宁静的立方根。",
    ": Electric Vigor": "：电子活力",
    ": Invoke Glory": "：援引荣耀",
    "Advanced Potion Making": "高级药水制作",
    "Barter for Star Fragments": "以物易物换取星星碎片",
    "Battle Doomsday": "世界末日之战",
    "Battle Galactus": "行星吞噬者之战",
    "Channel celestial light to inspire greatness.": "引导天光激发伟大。",
    "Create potions to enhance your combat prowess.": "创造药水来增强你的战斗能力。",
    "Engage the devourer of worlds in an epic showdown.": "在一场史诗般的对决中与世界的吞噬者交战。",
    "Escape the dazzling glow and step into the ultimate frontier.": "逃离耀眼的光芒，步入终极边界。",
    "Establish your authority over celestial forces.": "建立你对天界力量的权威。",
    "Exit to Neon Hypergrid": "退出霓虹超网格",
    "Extract Pixel Data": "提取像素数据",
    "Gather shimmering remnants of ancient stars.": "收集远古恒星的残余物。",
    "Illuminate Virtual Vistas": "照亮虚拟远景",
    "Leave divine order behind and step into radiant energy.": "将神圣秩序抛在身后，步入辐射能量。",
    "Overclock Digital Circuits": "超频数字电路",
    "Proclaim Divine Edicts": "宣讲圣谕",
    "Rally celestial forces into one harmonious chorus.": "将天上的力量凝聚成一个和谐的合唱。",
    "Shift to Omega Expanse": "转向欧米伽扩张",
    "Sync with Digital Frequencies": "数字频率同步",
    "Tune into the electric pulse of the grid.": "调谐到电网的电脉冲中。",
    "Unify Stellar Legions": "统一恒星军团",
    "Unleash radiant creativity through digital artistry.": "通过数字艺术释放璀璨的创造力。",
    "Battle HAL 9000": "HAL 9000之战",
    "Battle T-800": "T-800之战",
    ": Evoke Inspiration": "：激发灵感",
    ": Harmonize Chaos": "：调和混乱",
    ": Resonate with Cosmos": "：与宇宙共鸣",
    "5x experience gain next 2 tasks": "下两个任务获得5倍经验值",
    "75% for next 2 tasks": "75%用于下两个任务",
    "and reduced energy drain by 23%.": "减少了23%的能量消耗。",
    "Boosted Combat speed and reduced energy drain by 150%.": "提高战斗速度，减少150%的能量消耗。",
    "Challenge the legendary AI in a clash of wits.": "在斗智斗勇中挑战传说中的AI。",
    "Channel raw cosmic power into your arsenal.": "将原始的宇宙力量引入你的武器库。",
    "Compile Data Clusters": "编译数据集群",
    "Darth Vader defeated! +56 Power": "击败了达斯·维德！+ 56权力",
    "Decode Alien Frequencies": "解码外星频率",
    "Decrypt Virtual Codes": "解密虚拟代码",
    "Depart to Infinite Horizon": "驶向无限地平线",
    "Engage the relentless cyborg in a test of survival.": "与无情的半机械人交战，进行生存考验。",
    "Enhance connectivity within the digital realm.": "加强数字领域互联互通。",
    "Ensure harmony amid chaotic energies.": "在混乱的能量中确保和谐。",
    "Exit the digital cloud and step toward endless possibility.": "退出数字云，走向无限可能。",
    "Feel the heartbeat of the universe.": "感受宇宙的心跳。",
    "Gained +1 of held resources.": "获得+1持有资源",
    "Gather and organize fragmented digital info.": "收集和组织碎片化的数字信息。",
    "Gather fragmented bits of digital information.": "收集零碎的数字信息。",
    "Harness Expanse Energy": "利用广阔能源",
    "Interpret mysterious signals from beyond.": "解读来自远方的神秘信号。",
    "Let visions of code inspire new realities.": "让代码的愿景激发新的现实。",
    "Lightsaber": "光剑",
    "Magnifying Glass": "放大镜",
    "Merge your vision with digital artistry.": "将你的视觉与数字艺术相结合。",
    "Recover valuable remnants from forgotten networks.": "从被遗忘的网络中恢复有价值的残余。",
    "Reduces energy drain by 1000% for Endurance.": "减少耐力消耗1000%的能量。",
    "Reduces energy drain by 50%": "减少50%的能量消耗",
    "Scavenge Cyber Relics": "清理网络文物",
    "Step from the vast expanse into an enigmatic digital cloud.": "从广阔的空间步入神秘的数字云。",
    "Streamline Virtual Networks": "精简虚拟网络",
    "Sync with Pixel Patterns": "与像素模式同步",
    "Tinkering, Hacking": "铸补,黑客",
    "Unlock hidden messages in streams of data.": "解锁数据流中的隐藏消息。",
    "Venture to Digital Nebula": "探索数字星云",
    " is 50% faster.": "速度快了50%。",
    ", Combat, Intellect": "，战斗，智力",
    ", Nihility": "，虚无",
    ": Resonate": "：共鸣",
    "(does not affect Totality)": "（不影响整体）",
    "75% for next 7 tasks": "75%用于接下来的7个任务",
    "75% for next task": "75%用于下一个任务",
    "Absorb the profound silence and insights of nothingness.": "吸收深邃的寂静和虚无的洞察力。",
    "Battle Kaguya": "月神之战",
    "Channel the void’s mysterious reverberations.": "引导虚空的神秘回响。",
    "Copium Check": "精神检查",
    "Distill Absurdity": "蒸馏荒谬",
    "Echo of Nothing: Invoke the Void": "无物回响：召唤虚空",
    "Embrace the Void's Wisdom": "拥抱虚空的智慧",
    "Engage in an epic confrontation with Kaguya.": "与女神进行一场史诗般的对抗。",
    "Extract meaning from the chaos of the void.": "从混沌的虚空中提取意义。",
    "Leave the emptiness behind and ascend toward ultimate revelation.": "把空虚抛在脑后，向终极启示升华。",
    "Next time you prestige, start with +500 energy (first run only).": "下次你声望时，以+500能量开始（仅限首次运行）。",
    "One must transcend above Copium to exit the void.": "一个人必须超越精神才能离开虚空。",
    "Practice Kamui with Kakashi": "和卡卡西一起练习神井",
    "Slay the bitch and take her eye.": "杀了那贱人，取下她的眼睛。",
    "Soar to Eternal Apex": "飞向永恒的顶点",
    "Vibrate with the rhythm of utter nothingness.": "随着完全虚无的节奏振动。",
    "What a guy.": "真是个好男人。",
    "Make every game tick count as 20% more.": "让每一场游戏的Tick计数增加20%。",
    "Your delusion is over 9000!": "你的妄想超过9000！",
    ": Drift Through": "：漂移",
    "(in theory can propagate infinitely)": "（理论上可以无限传播）",
    "200% for Perception, Intellect, Hacking, and Cybernetics.": "感知，智力，黑客和控制论200%",
    "25% chance to spawn a random resource used in this run.": "有25%的几率生成一个随机资源。",
    "5x experience gain next 3 tasks": "在接下来的3个任务中获得5倍的经验",
    "75% for next 5 tasks": "75%用于接下来的5个任务",
    "Augment Fuel": "补充燃料",
    "Battle Godzilla": "哥斯拉之战",
    "Blades Of Chaos": "混乱之刃",
    "Boosted Combat speed and reduced energy drain by 225%.": "提高战斗速度，减少225%的能量消耗。",
    "Break Finite Limits": "突破有限极限",
    "Breakthrough to Ethereal Matrix": "突破以太矩阵",
    "Changes lambda parameter for delusion gain from 0.5 to 0.25.": "将妄想增益的lambda参数从0.5更改为0.25。",
    "Channel the energy of infinity into your being.": "引导无限的能量进入你的存在。",
    "Collect ancient insights from the cosmos.": "从宇宙中收集古老的见解。",
    "Each time you advance a zone,": "每次你前进一个区域，",
    "Embark on the ultimate rebirth by transcending chaos - a ritual that reshapes your destiny.": "通过超越混乱开始最终的重生-一个重塑你命运的仪式。",
    "Embody Cosmic Potential": "体现宇宙潜能",
    "Engage the king of monsters in a titanic struggle.": "在一场巨大的斗争中与怪物之王交战。",
    "Float among the endless expanse of space.": "漂浮在浩瀚无垠的太空中。",
    "Harvest Cosmic Scrolls": "收割宇宙卷轴",
    "Let the boundless energy of the universe fuel your knowledge of cybernetics.": "让宇宙的无限能量为你的控制论知识加油吧。",
    "Push beyond the boundaries of the known universe.": "超越已知宇宙的边界。",
    "Saiyan Armor": "赛亚盔甲",
    "Shatter your limits and cross into the unknown.": "打破你的极限，跨入未知。",
    "Spark of Infinity: Cyber Enhancement": "无限火花：网络增强",
    "This increases delusion gain.": "这增加了错觉的增益。",
    "When hacking levels up, 13% chance for tinkering to also level up.": "当黑客升级，13%的机会铸补也升级。",
    "When tinkering levels up, 13% chance for hacking to also level up.": "当铸补升级时，13%的几率黑客也会升级。",
    ": Matrix Miracles": "：《黑客帝国》",
    "A relentless swarm of Agent Smiths — endless, inescapable, inevitable.": "一群无情的史密斯特工——没完没了，无法逃脱，不可避免。",
    "Battle Googol Smith": "古戈尔·史密斯之战",
    "Blend imagination with binary data.": "将想象力与二进制数据相结合。",
    "Decode Ethereal Enigmas": "解码以太谜题",
    "Exit the digital realm and jump into time’s mysterious currents.": "离开数字世界，跳入时间神秘的洪流中。",
    "Extract Dream Fragments": "提取梦境片段",
    "Gather rare remnants of lucid dreams.": "收集稀有的清醒梦的残余。",
    "Harmonize with the underlying code of existence.": "与存在的基本法则协调一致。",
    "Leap to Temporal Paradox": "跳跃到时间悖论",
    "Manifest unexpected wonders from the code.": "从代码中显示意想不到的奇迹。",
    "Merge with the Digital Spirit": "与数字精神融合",
    "Solve the riddles of a shifting digital realm.": "解决不断变化的数字领域的谜题。",
    "Synthesize Virtual Realities": "合成虚拟现实",
    "Boost the power of virtual infrastructures.": "增强虚拟基础设施的力量。",
    ": Chrono Clarity": "：时空清晰",
    ": Spawned Omega Resonator": "：生成了欧米伽共鸣器",
    "150% for Perception, Intellect, Hacking, and Cybernetics.": "感知，智力，黑客和控制论150%",
    "3 extra lightsabers spawned!": "3个额外的光剑！",
    "75% for next 3 tasks": "75%留给接下来的3个任务",
    "Align fragmented memories across eras.": "整理不同时代的碎片记忆。",
    "Analyze the distortions in time’s fabric.": "分析时间结构的扭曲。",
    "Battle Pudge": "战斗矮胖的人",
    "Capture Time Fragments": "捕捉时间片段",
    "Focus your mind to see through time.": "集中你的注意力去看透时间。",
    "Hooks fly from the shadows — sudden, brutal, and impossible to dodge.": "钩子从阴影中飞来-突然，残酷，不可能躲避。",
    "Manipulate echoes of the past.": "操纵过去的回声。",
    "Measure Shifting Chronologies": "测量变化的年表",
    "Navigate to Ultra Dimension": "导航到超维度",
    "Rewind Digital Echoes": "倒带数字回声",
    "Secure remnants of fleeting time.": "保护时光流逝的残余物。",
    "Step from warped time into a realm of infinite possibilities.": "从扭曲的时间进入无限可能的领域。",
    "Synchronize Lost Moments": "同步丢失力矩",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Zone 29: Transcendent Void": "区域29：超越虚空",
    "Zone 27: Temporal Paradox": "区域27：时间悖论",
    "Zone 26: Ethereal Matrix": "区域26：空灵矩阵",
    "Zone 25: Infinite Horizon": "区域25：无限时域",
    "Zone 24: Digital Nebula": "区域24：数字星云",
    "Zone 23: Omega Expanse": "区域23：欧米伽扩张",
    "Zone 22: Neon Hypergrid": "区域22：霓虹超级电网",
    "Zone 21: Celestial Dominion": "区域21：天体统治",
    "Zone 20: Cosmic Forge": "区域20：宇宙熔炉",
    "Zone 19: Cybernetic Olympus": "区域19：控制奥林匹斯",
    "Zone 18: Quantum Abyss": "区域18：量子深渊",
    "Zone 17: Nebular Nexus": "区域17：星云联结",
    "Zone 16: The Garden": "区域16：花园",
    "Zone 15: Nexus of Infinity": "第15区：无限的联系",
    "Zone 14: Exalting Metropolis": "区域14：提升大都会",
    "Zone 13: Shattered Expanse": "区域13：破碎苍穹",
    "Zone 12: Forsaken Bastion": "区域12：被遗忘的堡垒",
    "Zone 11: Research Facility": "区域11：研究设施",
    "Zone 10: Techno District": "区域10：科技区",
    "Zone 9: Digital Underground": "区域9：数字地下",
    "Zone 8: Rooftop Rendezvous": "区域8：天台汇合",
    "Zone 7: Abandoned Factory": "区域7：废弃工厂",
    "Zone 6: Combat Arena": "区域6：战斗竞技场",
    "Zone 5: Cyber Lab": "区域5: 网络实验室",
    "Zone 4: Corporate District": "区域4: 公司区域",
    "Zone 3: City Core": "区域3: 城市核心",
    "Zone 2: Urban Outskirts": "区域2: 城市郊区",
    "Zone 1: Beginner’s Bootcamp": "区域1: 初学者训练营",
    "Kuzzi Games Discord": "Kuzzi Games Discord",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "★": "★",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Energy Drain: ": "能量消耗:",
    "Copium Reactor": "精神反应堆",
    "Travel: ": "旅行: ",
    "Speed: ": "速度: ",
    "Tinkering": "铸补",
    "XP: ": "经验值: ",
    "Estimated Time: ": "预计时间：",
    "Estimated Time for next task: ": "下次任务预计时间：",
    "Endurance": "耐力",
    "Uses: ": "使用: ",
    "Basic Mech": "基本机械",
    "Brewmaster": "酿酒师",
    "Celestial Light": "天光",
    "Completionist": "完美主义者",
    "Copious Alchemist": "丰富的炼金术士",
    "Crypto Wallet": "加密钱包",
    "Cyber Boost": "赛博加成",
    "Digital Dreams": "数字梦想",
    "Dimension Mastery": "次元精通",
    "Double Timer": "双计时器",
    "Echo Of Nothing": "无物回响",
    "Energetic Bliss": "元气极乐",
    "Expanse Echo": "苍穹回声",
    "Forge Fervor": "锻造激情",
    "Four Leaf Clover": "四叶草",
    "Futuristic Wrench": "未来扳手",
    "Gacha Machine": "扭蛋机",
    "Growth Miracle": "生长奇迹",
    "Healthy Living": "健康生活",
    "Hoverboard": "悬浮滑板",
    "Immunity Device": "免疫装置",
    "Inspired Glow": "激发辉光",
    "Knowledge Preserver": "知识守护者",
    "Kung Fu Zen": "功夫禅宗",
    "Last Stand": "最后一站",
    "Master Of Ai": "Ai大师",
    "Mechanical Genius": "机械天才",
    "Neon Energy": "霓虹能量",
    "Neural Matrix": "神经矩阵",
    "Nihilistic Beats": "虚无的节拍",
    "Noob Haxor": "新手Haxor",
    "Omega Stability": "欧米伽稳定性",
    " Harmony": "和声",
    " Teleportation": "传送",
    " Vitalizer": "激活器",
    "Reinforcement Learning": "强化学习",
    "Rex": "国王",
    "Perception": "感知",
    "Intellect": "智力",
    "Sandstorm": "沙尘暴",
    "Self Operating Gadget": "自动操作装置",
    "Simulation Engine": "模拟引擎",
    "Spark Of Infinity": "无限火花",
    "Spectral Glow": "光谱辉光",
    "Stellar Dreams": "星辰之梦",
    "Time Glimpse": "时光一瞥",
    "Universal Alloy": "通用合金",
    "Urban Warfare": "城市战争",
    "Wise Mechanic": "明智的机械师",
    "Workaholic": "工作狂",
    "Task XP Multiplier: ": "任务经验乘数: ",
    "Charisma": "魅力",
    "Alchemy": "炼金术",
    "Travel": "旅行",
    "Boosted Perception by ": "感知提升 ",
    "Achievement: ": "成就: ",
    "(Task Progress Mult: ": "(任务进度乘数: ",
    "Energy: ": "能量: ",
    "Energy drains based on each skill used.": "能量消耗取决于所使用的技能。",
    "Task Speed Multiplier: ": "任务速度乘数: ",
    "Task Drain Multiplier: ": "任务消耗乘数: ",
    "Mechanics": "机械",
    "Knowledge Gain on Completion: ": "完成后的知识增益: ",
    "Hacking": "入侵",
    "Combat": "战斗",
    "Reduce all energy drain by ": "减少所有能量消耗 ",
    "Reduces Alchemy energy drain by ": "减少炼金术的能量消耗",
    "Increases starting Energy by ": "增加初始能量 ",
    "Cybernetics": "控制",
    "Negotiation": "谈判",
    "Copium Gain for next Task: ": "下一个任务的精神增益：",
    "Power Gain on Completion: ": "完成时力量增益：",
    "Reduced Alchemy energy drain by ": "减少炼金术的能量消耗 ",
    "Reduced Hacking energy drain by ": "减少入侵的能量消耗 ",
    "Reduced Tinkering and Hacking energy drain by ": "减少铸补和入侵的能量消耗 ",
    "Reduced Cybernetics energy drain by ": "减少控制能量消耗 ",
    "AiMastery": "Ai精通",
    "Quantum": "量子",
    "Serenity:": "宁静:",
    "Omniscience": "全知",
    "Current Effect: ": "当前效果: ",
    "Current Resets: ": "当前重置: ",
    "Cost: ": "成本: ",
    "Reduced Endurance and Combat energy drain by ": "减少耐力和战斗能量消耗 ",
    "Reduced Delusion by ": "减少妄想 ",
    "Reduced Copium by ": "减少精神 ",
    "Copium reduced by ": "精神减少 ",
    "Energy increased by ": "能量增加 ",
    "Boosts Quantum speed by ": "提升量子速度 ",
    "Boosted Travel speed by ": "提升了旅行速度 ",
    "Reduced Combat and Quantum energy drain by ": "减少战斗和量子能量消耗 ",
    "Boosts Travel speed by ": "提升旅行速度 ",
    "Surveillance Core": "监测核心",
    "Reduced Copium gain by ": "降低 精神 增益 ",
    "Reduces Copium gain by ": "降低 精神 增益 ",
    "Reduced energy drain by ": "降低 能量 消耗 ",
    "Reduced Combat energy drain by ": "降低 战斗能量 消耗 ",
    "Reduce Combat energy drain by ": "降低 战斗能量 消耗 ",
    "Boosted Omniscience speed by ": "提升全知速度 ",
    "Boosted Tinkering progress by ": "提升铸补进度 ",
    "Celestial Blossom": "天体开花",
    "Cybernetic Armor x": "控制盔甲 x",
    "Cosmic Shard": "宇宙碎片",
    "Celestial Ore": "天体矿石",
    "All skills' speed increased by ": "全部技能速度提高 ",
    "Adamantium": "艾德曼合金",
    "Multiplies knowledge gain by ": "乘以知识增益 ",
    "Kratos defeated! ": "托斯被击败了！",
    "Dojo Master Chuck Norris defeated! ": "道场大师查克·诺里斯被击败了！",
    "Whenever another skill gains xp, Quantum gains 1% of that xp.": "当其他技能获得经验值时，量子获得1%的经验值。",
    "Thanos (with hair) defeated! ": "灭霸（长头发的）被击败了！",
    "Deadpool defeated! ": "死侍 已被击败！",
    "Big Brother defeated! ": "老大哥 已被击败！",
    "Isshin defeated! ": "伊信 已被击败！",
    "Kratos defeated! ": "奎托斯 已被击败！",
    "Vegeta defeated! ": "贝吉塔 已被击败！",
    "Sauron defeated! ": "索伦被击败了！",
    "Doctor Manhattan defeated! ": "曼哈顿博士被击败了！",
    "Shao Kahn defeated! ": "少卡恩已被击败！",
    "Dojo Master Chuck Norris defeated! ": "道场大师查克·诺里斯被击败了！",
    "Agent Smith defeated! ": "史密斯探员被击败了！",
    "All XP gains increased by ": "所有经验增益增加 ",
    "Ultron defeated! ": "奥创被击败了！",
    "Unicron defeated! ": "宇宙大帝已被击败！",
    "Sanity Cleanser x": "健康洁面 x",
    "Katana x": "武士刀 x",
    "Blades Of Chaos x": "混乱之刃 x",
    "Nihility": "虚无",
    "Totality": "整体",
    "Beating Heart x": "跳动的心脏 x",
    "and reduced energy drain by ": "并减少能量消耗 ",
    "Delusion reduced by ": "妄想减少 ",
    "Galactus defeated! ": "行星吞噬者被击败了！",
    "Reduced Endurance energy drain by ": "减少耐力能量消耗 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    " (Level: ": " (等级: ",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " unlocked": " 已解锁",
    "% of a level": "% 的等级",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\%.$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)\)$/,
    /^([\d\.]+)(.+)\)$/,
    /^x([\d\.]+)K$/,
    /^x([\d\.]+)M$/,
    /^x([\d\.]+)B$/,
    /^x([\d\.]+)T$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^x([\d\.]+)Qa$/,
    /^x([\d\.]+)Qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+) tick$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)e\-([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You lose (.+) of your Power.$/, '你失去了 $1 你的力量。'],
    [/^This is your (.+) Delusion reset.$/, '这是你第 $1 次妄想重置。'],
    [/^All progress will reset, but you gain (.+) Serenity.$/, '所有进度将重置，但你获得 $1 宁静。'],
    [/^Best Zone Completed: (.+) \| \n(.+)Resets on Completion: (.+)$/, '最佳区域完成：$1 | \n完成时重置：$3'],
    [/^Delusion Gain for next Task: (.+) \(random, skewed to low\)$/, '下一个任务的妄想增益：$1（随机，偏低）'],
    [/^Zone (.+) completed (.+) times.$/, '区域 $1 完成 $2 次.'],
    [/^New best fully compeleted: Zone (.+) with (.+) resets$/, '全新最佳完成：区域 $1 重置 $2 次'],
    [/^: (.+) of a level$/, ': 一级的 $1'],
    [/^But you permanently gain (.+) starting energy.$/, '但你会永久获得 $1 初始能量。'],
    [/^This is your (.+) Copium reset.$/, '这是你的第 $1 次精神重置。'],
    [/^This is your (.+) Energy reset.$/, '这是你的第 $1 次能量重置。'],
    [/^Click to gain (.+) Energy.$/, '点击获得 $1 能量。'],
    [/^Boosted speed by (.+) for Charisma and Tinkering.$/, '魅力和铸补的速度提高$1。'],
    [/^Boosts speed by (.+) for Charisma and Tinkering.$/, '魅力和铸补的速度提高$1。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^was ([\d\.]+)\% chance to gain ([\d\.,]+) Power$/, '有 $1\% 几率获得 $2 力量'],
    [/^was ([\d\.]+)\% chance to gain ([\d\.,]+) Knowledge$/, '有 $1\% 几率获得 $2 知识'],
    [/^was ([\d\.]+)\% chance to gain ([\d\.,]+) Energy$/, '有 $1\% 几率获得 $2 能量'],
    [/^([\d\.]+)\% chance to gain ([\d\.,]+) Delusion$/, '$1\% 几率获得 $2 妄想'],
    [/^([\d\.]+)\% chance to gain ([\d\.,]+) Copium$/, '$1\% 几率获得 $2 精神'],
    [/^([\d\.]+)\% chance to gain ([\d\.,]+) Knowledge$/, '$1\% 几率获得 $2 知识'],
    [/^([\d\.]+)\% chance to gain ([\d\.,]+) Power$/, '$1\% 几率获得 $2 力量'],
    [/^([\d\.]+)\% chance to gain ([\d\.,]+) Energy$/, '$1\% 几率获得 $2 能量'],
    [/^([\d\.]+)\% chance to lose ([\d\.,]+) Copium$/, '$1\% 几率失去 $2 精神'],
    [/^([\d\.]+)\% chance to lose ([\d\.,]+) Delusion$/, '$1\% 几率失去 $2 妄想'],
    [/^Boosted Charisma speed by ([\d\.]+)\%. Reduced Negotiation energy drain by (.+).$/, '提升魅力速度 $1\%。减少谈判能量消耗 $2。'],
    [/^Boosted Combat speed by ([\d\.]+)\%. Reduced Perception energy drain by (.+).$/, '提升战斗速度 $1\%。减少感知能量消耗 $2。'],
    [/^Boosted Quantum speed by ([\d\.]+)\%.$/, '提升量子速度 $1\%.'],
    [/^Boosted Combat speed by ([\d\.]+)\%.$/, '提升战斗速度 $1\%.'],
    [/^Version: ([\d\.]+)$/, '版本: $1'],
    [/^([\d\.]+) s$/, '$1 秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+) m ([\d\.]+) s$/, '$1 分 $2 秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) and Delusion by ([\d\.,]+).$/, '$1 和 妄想 $2。'],
    [/^Highest Zone Completed: ([\d\.,]+) \| Zone ([\d\.,]+) Potential Serenity: $/, '最高完成区域：$1 | 区域 $2 潜在宁静：'],
    [/^([\d\.,]+) \| Copium: ([\d\.,]+) \| Delusion: ([\d\.,]+)$/, '$1 | 精神: $2 | 妄想: $3'],
    [/^ \(Level: ([\d\.,]+)\)$/, ' (等级: $1)'],
    [/^ \+([\d\.,]+) \(Level: ([\d\.,]+)\)$/, ' \+$1 (等级: $2)'],
    [/^ \+([\d\.,]+) \(Level: ([\d\.,]+)\).$/, ' \+$1 (等级: $2).'],
    [/^ \+([\d\.,]+) \(Lvl: ([\d\.,]+)\).$/, ' \+$1 (等级: $2).'],
    [/^ \+([\d\.,]+) \(Lvl ([\d\.,]+)\).$/, ' \+$1 (等级 $2).'],
    [/^ \+([\d\.,]+) \(Lvl ([\d\.,]+)\)$/, ' \+$1 (等级 $2)'],
    [/^: \-([\d\.,]+) Copium$/, ': \-$1 精神'],
    [/^: \-([\d\.,]+) Delusion$/, ': \-$1 妄想'],
    [/^: \+([\d\.,]+) Energy$/, ': \+$1 能量'],
    [/^: \+([\d\.,]+) Power$/, ': \+$1 力量'],
    [/^: Unlock perk on Zone ([\d\.,]+).$/, '：解锁区域 $1 的特权。'],
    [/^\+([\d\.,]+) levels$/, '\+$1 等级'],
    [/^\+([\d\.,]+) level$/, '\+$1 等级'],
    [/^\+([\d\.,]+) Power$/, '\+$1 力量'],
    [/^(.+)leveled up to ([\d\.,]+)$/, '$1 升级到了 $2'],
    [/^Gained ([\d\.,]+) Energy.$/, '获得 $1 能量。'],
    [/^Used ([\d\.,]+) Random Crystals. Leveled up:$/, '使用了 $1 随机晶体。升级：'],
    [/^Used ([\d\.,]+) Random Crystal. Leveled up:$/, '使用了 $1 随机晶体。升级：'],
    [/^Used ([\d\.,]+) Goggles.$/, '使用了 $1 护目镜。'],
    [/^Used ([\d\.,]+) Blades of Chaos.$/, '使用了 $1 混乱之刃。'],
    [/^Used ([\d\.,]+) One Ring.$/, '使用了 $1 一戒。'],
    [/^Used ([\d\.,]+) One Rings.$/, '使用了 $1 一戒。'],
    [/^Used ([\d\.,]+) Steroidss.$/, '使用了 $1 类固醇。'],
    [/^Used ([\d\.,]+) Steroids.$/, '使用了 $1 类固醇。'],
    [/^Used ([\d\.,]+) Adamantium.$/, '使用了 $1 艾德曼合金。'],
    [/^Used ([\d\.,]+) Lightsaber.$/, '使用了 $1 光剑。'],
    [/^Used ([\d\.,]+) Lightsabers.$/, '使用了 $1 光剑。'],
    [/^Used ([\d\.,]+) Surveillance Core.$/, '使用了 $1 监测核心。'],
    [/^Used ([\d\.,]+) Surveillance Cores.$/, '使用了 $1 监测核心。'],
    [/^Used ([\d\.,]+) Stardust. Created:$/, '使用了 $1 星尘. 创建了:'],
    [/^Used ([\d\.,]+) Stardusts. Created:$/, '使用了 $1 星尘. 创建了:'],
    [/^Used ([\d\.,]+) Quantum Residue.$/, '使用了 $1 量子残基。'],
    [/^Used ([\d\.,]+) Quantum Residues.$/, '使用了 $1 量子残基。'],
    [/^Used ([\d\.,]+) Puzzle Piece.$/, '使用了 $1 拼图碎片。'],
    [/^Used ([\d\.,]+) Puzzle Pieces.$/, '使用了 $1 拼图碎片。'],
    [/^Used ([\d\.,]+) Adamantiums.$/, '使用了 $1 艾德曼合金。'],
    [/^Used ([\d\.,]+) Cosmic Shard.$/, '使用了 $1 宇宙碎片。'],
    [/^Used ([\d\.,]+) Cosmic Shards.$/, '使用了 $1 宇宙碎片。'],
    [/^Used ([\d\.,]+) Celestial Blossom.$/, '使用了 $1 天体开花。'],
    [/^Used ([\d\.,]+) Celestial Blossoms.$/, '使用了 $1 天体开花。'],
    [/^Used ([\d\.,]+) Celestial Ore.$/, '使用了 $1 天体矿石。'],
    [/^Used ([\d\.,]+) Celestial Ores.$/, '使用了 $1 天体矿石。'],
    [/^Used ([\d\.,]+) Nano Component.$/, '使用了 $1 纳米成分。'],
    [/^Used ([\d\.,]+) Nano Components.$/, '使用了 $1 纳米成分。'],
    [/^Used ([\d\.,]+) Touchable Grasses.$/, '使用了 $1 可触碰的草。'],
    [/^Used ([\d\.,]+) Touchable Grass.$/, '使用了 $1 可触碰的草。'],
    [/^Used ([\d\.,]+) Hoverboard Fuel.$/, '使用了 $1 悬浮滑板燃料。'],
    [/^Used ([\d\.,]+) Hoverboard Fuels.$/, '使用了 $1 悬浮滑板燃料。'],
    [/^Used ([\d\.,]+) Katanas.$/, '使用了 $1 武士刀。'],
    [/^Used ([\d\.,]+) Katana.$/, '使用了 $1 武士刀。'],
    [/^Used ([\d\.,]+) Infinity Gauntlet.$/, '使用了 $1 无限手套。'],
    [/^Used ([\d\.,]+) Infinity Gauntlets.$/, '使用了 $1 无限手套。'],
    [/^Used ([\d\.,]+) Beating Hearts.$/, '使用了 $1 跳动的心脏。'],
    [/^Used ([\d\.,]+) Beating Heart.$/, '使用了 $1 跳动的心脏。'],
    [/^Used ([\d\.,]+) Sanity Cleansers.$/, '使用了 $1 健康清洁剂。'],
    [/^Used ([\d\.,]+) Sanity Cleanser.$/, '使用了 $1 健康清洁剂。'],
    [/^Used ([\d\.,]+) Augment Fuels.$/, '使用了 $1 补充燃料。'],
    [/^Used ([\d\.,]+) Augment Fuel.$/, '使用了 $1 补充燃料。'],
    [/^Used ([\d\.,]+) Saiyan Armor.$/, '使用了 $1 赛亚人盔甲。'],
    [/^Used ([\d\.,]+) Saiyan Armors.$/, '使用了 $1 赛亚人盔甲。'],
    [/^Used ([\d\.,]+) Karate Belt.$/, '使用了 $1 空手道腰带。'],
    [/^Used ([\d\.,]+) Karate Belts.$/, '使用了 $1 空手道腰带。'],
    [/^Used ([\d\.,]+) Omega Resonator.$/, '使用了 $1 欧米伽谐振器。'],
    [/^Used ([\d\.,]+) Omega Resonators.$/, '使用了 $1 欧米伽谐振器。'],
    [/^Used ([\d\.,]+) Cybernetic Potions.$/, '使用了 $1 控制药水。'],
    [/^Used ([\d\.,]+) Cybernetic Potion.$/, '使用了 $1 控制药水。'],
    [/^Used ([\d\.,]+) Cybernetic Armors.$/, '使用了 $1 控制盔甲。'],
    [/^Used ([\d\.,]+) Cybernetic Armor.$/, '使用了 $1 控制盔甲。'],
    [/^Used ([\d\.,]+) Shiny Helmet.$/, '使用了 $1 闪亮头盔。'],
    [/^Used ([\d\.,]+) Shiny Helmets.$/, '使用了 $1 闪亮头盔。'],
    [/^Used ([\d\.,]+) Amphetamine Pills.$/, '使用了 $1 安非他命药丸。'],
    [/^Used ([\d\.,]+) Amphetamine Pill.$/, '使用了 $1 安非他命药丸。'],
    [/^Used ([\d\.,]+) Cool Sunglasses.$/, '使用了 $1 酷的太阳镜。'],
    [/^Used ([\d\.,]+) Energy Elixir.$/, '使用了 $1 能量药剂。'],
    [/^Used ([\d\.,]+) Energy Elixirs.$/, '使用了 $1 能量药剂。'],
    [/^Used ([\d\.,]+) Magnifying Glass.$/, '使用了 $1 放大镜。'],
    [/^Used ([\d\.,]+) Magnifying Glasses.$/, '使用了 $1 放大镜。'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^Level: (.+), Cost: (.+)$/, '等级: $1, 成本: $2'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);